"""
phase2/models.py

Data models for Phase 2: Parallel Synthesis.
Defines structures for partial domains and PDDL components.
"""

from dataclasses import dataclass, field
from typing import Optional
import json


@dataclass
class PDDLType:
    """PDDL type definition."""
    name: str
    parent: Optional[str] = "object"
    source: str = ""

    def to_dict(self) -> dict:
        return {
            "name": self.name,
            "parent": self.parent,
            "source": self.source,
        }


@dataclass
class PDDLPredicate:
    """PDDL predicate definition."""
    name: str
    parameters: list[tuple[str, str]] = field(default_factory=list)
    source: str = ""

    def to_dict(self) -> dict:
        return {
            "name": self.name,
            "parameters": self.parameters,
            "source": self.source,
        }

    def to_pddl(self) -> str:
        """Generate PDDL predicate string."""
        if self.parameters:
            params = " ".join(f"?{p[0]} - {p[1]}" for p in self.parameters)
            return f"({self.name} {params})"
        return f"({self.name})"


@dataclass
class PDDLAction:
    """PDDL action definition."""
    name: str
    parameters: list[tuple[str, str]] = field(default_factory=list)
    preconditions: list[str] = field(default_factory=list)
    effects: list[str] = field(default_factory=list)
    command_template: str = ""
    requires_root: bool = False
    source_utility: str = ""
    source_worker: str = ""

    def to_dict(self) -> dict:
        return {
            "name": self.name,
            "parameters": self.parameters,
            "preconditions": self.preconditions,
            "effects": self.effects,
            "command_template": self.command_template,
            "requires_root": self.requires_root,
            "source_utility": self.source_utility,
            "source_worker": self.source_worker,
        }

    def to_pddl(self) -> str:
        """Generate PDDL action string."""
        lines = [f"(:action {self.name}"]

        # Parameters
        params = " ".join(f"?{p[0]} - {p[1]}" for p in self.parameters)
        lines.append(f"  :parameters ({params})")

        # Preconditions
        if self.preconditions:
            lines.append("  :precondition (and")
            for pre in self.preconditions:
                lines.append(f"    {pre}")
            lines.append("  )")
        else:
            lines.append("  :precondition (and)")

        # Effects
        if self.effects:
            lines.append("  :effect (and")
            for eff in self.effects:
                lines.append(f"    {eff}")
            lines.append("  )")
        else:
            lines.append("  :effect (and)")

        lines.append(")")
        return "\n".join(lines)


@dataclass
class PartialPDDLDomain:
    """
    Partial PDDL domain generated by a worker.
    Contains types, predicates, and actions for a utility group.
    """
    worker_name: str
    group_name: str
    types: list[PDDLType] = field(default_factory=list)
    predicates: list[PDDLPredicate] = field(default_factory=list)
    actions: list[PDDLAction] = field(default_factory=list)
    raw_pddl: str = ""
    error: Optional[str] = None
    generation_time: float = 0.0

    def to_dict(self) -> dict:
        return {
            "worker_name": self.worker_name,
            "group_name": self.group_name,
            "types": [t.to_dict() for t in self.types],
            "predicates": [p.to_dict() for p in self.predicates],
            "actions": [a.to_dict() for a in self.actions],
            "raw_pddl": self.raw_pddl,
            "error": self.error,
            "generation_time": self.generation_time,
        }

    def to_json(self, indent: int = 2) -> str:
        return json.dumps(self.to_dict(), indent=indent)

    @property
    def is_valid(self) -> bool:
        """Check if this partial domain has content and no errors."""
        has_content = bool(self.types or self.predicates or self.actions)
        return has_content and self.error is None
