from dataclasses import dataclass, field
from typing import Optional


@dataclass
class PDDLType:
    """Represents a PDDL type definition."""

    name: str
    parent: Optional[str] = None
    source: str = ""  # Which worker generated this


@dataclass
class PDDLPredicate:
    """Represents a PDDL predicate definition."""

    name: str
    parameters: list[tuple[str, str]]  # [(var_name, type_name), ...]
    description: str = ""
    source: str = ""


@dataclass
class PDDLAction:
    """Represents a PDDL action definition."""

    name: str
    parameters: list[tuple[str, str]]
    preconditions: list[str]
    effects: list[str]
    command_template: str = ""
    requires_root: bool = False
    source_utility: str = ""
    source_worker: str = ""


@dataclass
class PartialPDDLDomain:
    """Partial PDDL domain generated by a worker agent."""

    worker_name: str
    group_name: str
    types: list[PDDLType] = field(default_factory=list)
    predicates: list[PDDLPredicate] = field(default_factory=list)
    actions: list[PDDLAction] = field(default_factory=list)
    constants: list[tuple[str, str]] = field(default_factory=list)
    raw_pddl: str = ""
    generation_time: float = 0.0
    error: Optional[str] = None

    def to_dict(self) -> dict:
        return {
            "worker_name": self.worker_name,
            "group_name": self.group_name,
            "types": [{"name": t.name, "parent": t.parent} for t in self.types],
            "predicates": [
                {"name": p.name, "parameters": p.parameters} for p in self.predicates
            ],
            "actions": [
                {
                    "name": a.name,
                    "parameters": a.parameters,
                    "preconditions": a.preconditions,
                    "effects": a.effects,
                    "command": a.command_template,
                }
                for a in self.actions
            ],
            "generation_time": self.generation_time,
        }
