(define (problem sysadmin-initial)
  (:domain sysadmin)

  (:objects
    user_root user_sync user__apt user_nobody user_dhcpcd user_syslog user_usbmux user_kernoops user_dnsmasq user_cups-pk-helper user_cups-browsed user_gnome-initial-setup user_administrator user_sshd user_emmanuelli - user
    group_root group_adm group_cdrom group_sudo group_dip group_plugdev group_users group_nogroup group_syslog group_lpadmin group_administrator group_emmanuelli - group
    process_systemd process_nvidia-modeset_kthread_q process_nvidia-modeset_deferred_close_kthread_q process_rsyslogd process_networkmanager process_wpa_supplicant process_irq_94-nvidia process_nvidia process_nv_queue process_modemmanager process_sssd_be process_sssd_nss process_sssd_pam process_sssd_pac process_accounts-daemon process_cron process_systemd-logind process_kdevtmpfs process_kauditd process_khungtaskd process_oom_reaper process_kcompactd0 process_ksmd process_khugepaged process_irq_9-acpi process_irq_95-nvidia process_nvidia_1 process_nv_queue_1 process_oddjobd process_tailscaled process_unattended-upgr process_anydesk process_containerd process_sshd process_xrdp-sesman process_irq_30-dmar4-prq process_kswapd0 process_ecryptfs-kthread process_hwrng process_gdm3 process_uvm_global_queue process_uvm_deferred_release_queue process_uvm_tools_event_queue process_upowerd process_kthreadd process_pycharm process_cef_server process_nvidia-drm_timeline-4b process_nvidia-drm_timeline-4c process_dockerd process_kerneloops process_kerneloops_1 process_snapd process_osqueryd process_osqueryd_1 process_psimon process_irq_59-enp1s0 process_master process_scsi_eh_0 process_scsi_eh_1 process_scsi_eh_2 process_scsi_eh_3 process_containerd-shim process_containerd-shim_1 process_scsi_eh_4 process_scsi_eh_5 process_node process_startup_sh process_pool_workqueue_release process_scsi_eh_6 process_scsi_eh_7 process_cupsd process_cups-browsed process_docker-proxy process_docker-proxy_1 process_scsi_eh_8 process_usb-storage process_jbd2_sda-8 process_irq_62-pciehp process_docker-proxy_2 process_docker-proxy_3 process_ollama process_jbd2_nvme0n1p4-8 process_systemd-journal process_fwupd process_systemd-udevd process_psimon_1 process_gdm-session-wor process_systemd_1 process_nvidia-drm_timeline-37 process_nvidia-drm_timeline-38 process_irq_83-mei_me process_irq_84-idxd-misc process_jbd2_nvme0n1p1-8 process_auditd process_audit_prune_tree process_nv_queue_2 process_nv_queue_3 process_nv_open_q process_nv_open_q_1 process_networkd-dispat process_incrond process_power-profiles- process_sssd process_switcheroo-cont process_udisksd - process
    port_6_6188 port_6_631 port_6_53 port_6_11434 port_6_7070 port_6_3000 port_6_25 port_6_22 port_6_11436 port_6_6189 port_6_3350 port_6_3389 port_6_63342 port_17_53 port_17_5353 port_255_58 port_0_0 port_2054_0 - port
    service_wpa_supplicant_service service_systemd-tmpfiles-clean_service service_anydesk_service service_systemd-repart_service service_systemd-networkd-wait-online_service service_systemd-backlight_backlight_nvidia_0_service service_systemd-ask-password-wall_service service_systemd-journald_service service_systemd-journal-flush_service service_rsyslog_service service_cups-browsed_service service_kerneloops_service service_osqueryd_service service_keyboard-setup_service service_systemd-pcrphase_service service_systemd-tmpfiles-setup-dev-early_service service_systemd-resolved_service service_sssd_service service_systemd-user-sessions_service service_alsa-restore_service service_plymouth-quit-wait_service service_sssd-pam_service service_nvidia-persistenced_service service_systemd-fsck_dev-disk-by_x2duuid-f84e_x2dead2_service service_plymouth-read-write_service service_ssh_service service_openvpn_service service_snapd_seeded_service service_systemd-sysext_service service_systemd-logind_service service_systemd-rfkill_service service_snapd_apparmor_service service_sssd-autofs_service service_dbus_service service_systemd-udevd_service service_upower_service service_systemd-suspend_service service_postfix_service service_systemd-initctl_service service_systemd-sysctl_service service_modemmanager_service service_systemd-tpm2-setup_service service_user-runtime-dir_114505204_service service_systemd-modules-load_service service_networkmanager-wait-online_service service_systemd-vconsole-setup_service service_systemd-tmpfiles-setup-dev_service service_systemd-fsckd_service service_networkmanager_service service_xrdp-sesman_service service_snapd_core-fixup_service service_systemd-firstboot_service service_gdm_service service_snapd_system-shutdown_service service_systemd-pcrphase-sysinit_service service_systemd-pstore_service service_postfix_-_service service_incron_service service_systemd-tpm2-setup-early_service service_ollama_service service_systemd-suspend-then-hibernate_service service_systemd-soft-reboot_service service_accounts-daemon_service service_systemd-hibernate_service service_colord_service service_plymouth-start_service service_systemd-ask-password-plymouth_service service_lm-sensors_service service_systemd-binfmt_service service_systemd-udev-settle_service service_systemd-networkd_service service_sysstat-summary_service service_oddjobd_service service_fwupd_service service_systemd-hwdb-update_service service_sysstat-collect_service service_systemd-quotacheck_service service_sssd-pac_service service_sssd-nss_service service_systemd-hibernate-resume_service service_snapd_autoimport_service service_power-profiles-daemon_service service_snapd_recovery-chooser-trigger_service service_systemd-udev-trigger_service service_snapd_service service_systemd-oomd_service service_ubuntu-fan_service service_plymouth-quit_service service_sssd-sudo_service service_systemd-pcrmachine_service service_systemd-update-utmp-runlevel_service service_apparmor_service service_systemd-battery-check_service service_avahi-daemon_service service_cron_service service_gnome-remote-desktop_service service_systemd-journal-catalog-update_service service_xrdp_service service_auditd_service service_udisks2_service service_systemd-timesyncd_service service_systemd-bsod_service service_systemd-remount-fs_service service_systemd-random-seed_service service_switcheroo-control_service service_tailscaled_service service_console-setup_service service_cups_service service_plymouth-switch-root_service service_sysstat_service service_fwupd-refresh_service service_systemd-fsck_dev-disk-by_x2duuid-494638c4_x2d4d70_x2d4d12_x2db520_x2d52bfb646ce41_service service_setvtrgb_service service_apport-autoreport_service service_networkd-dispatcher_service service_snapd_snap-repair_service service_systemd-tmpfiles-setup_service service_snapd_failure_service service_kmod-static-nodes_service service_systemd-hybrid-sleep_service service_systemd-ask-password-console_service service_unattended-upgrades_service service_user_114505204_service service_systemd-pcrphase-initrd_service service_containerd_service service_systemd-sysusers_service service_apport_service service_systemd-update-done_service service_docker_service service_systemd-update-utmp_service service_systemd-machine-id-commit_service service_polkit_service service_rtkit-daemon_service service_sssd-ssh_service service_systemd-fsck-root_service - service
    package_anydesk package_apparmor package_apport package_auditd package_avahi-daemon package_colord package_console-setup package_containerd package_cron package_cups package_cups-browsed package_dbus package_docker_io package_fwupd package_gdm3 package_gnome-remote-desktop package_incron package_kerneloops package_kmod package_lm-sensors package_networkd-dispatcher package_oddjob package_openvpn package_osquery package_plymouth package_polkitd package_postfix package_power-profiles-daemon package_rsyslog package_rtkit package_snapd package_ssh-import-id package_sssd package_switcheroo-control package_sysstat package_systemd package_systemd-oomd package_systemd-resolved package_systemd-timesyncd package_tailscale package_ubuntu-fan package_udisks2 package_unattended-upgrades package_upower package_xrdp - package
    configuration_file__etc_incron_conf configuration_file__etc_kerneloops_conf configuration_file__etc_oddjobd_conf configuration_file__etc_rsyslog_conf - configuration_file
  )

  (:init
    (user_exists user_root)
    (can_escalate user_root)
    (user_critical user_root)
    (user_exists user_sync)
    (user_critical user_sync)
    (user_exists user__apt)
    (user_critical user__apt)
    (user_exists user_nobody)
    (user_exists user_dhcpcd)
    (user_critical user_dhcpcd)
    (user_exists user_syslog)
    (user_critical user_syslog)
    (user_exists user_usbmux)
    (user_critical user_usbmux)
    (user_exists user_kernoops)
    (user_critical user_kernoops)
    (user_exists user_dnsmasq)
    (user_critical user_dnsmasq)
    (user_exists user_cups-pk-helper)
    (user_critical user_cups-pk-helper)
    (user_exists user_cups-browsed)
    (user_critical user_cups-browsed)
    (user_exists user_gnome-initial-setup)
    (user_critical user_gnome-initial-setup)
    (user_exists user_administrator)
    (can_escalate user_administrator)
    (user_exists user_sshd)
    (user_critical user_sshd)
    (user_exists user_emmanuelli)
    (process_running process_systemd)
    (process_running process_nvidia-modeset_kthread_q)
    (process_running process_nvidia-modeset_deferred_close_kthread_q)
    (process_running process_rsyslogd)
    (process_running process_networkmanager)
    (process_running process_wpa_supplicant)
    (process_running process_irq_94-nvidia)
    (process_running process_nvidia)
    (process_running process_nv_queue)
    (process_running process_modemmanager)
    (process_running process_sssd_be)
    (process_running process_sssd_nss)
    (process_running process_sssd_pam)
    (process_running process_sssd_pac)
    (process_running process_accounts-daemon)
    (process_running process_cron)
    (process_running process_systemd-logind)
    (process_running process_kdevtmpfs)
    (process_running process_kauditd)
    (process_running process_khungtaskd)
    (process_running process_oom_reaper)
    (process_running process_kcompactd0)
    (process_running process_ksmd)
    (process_running process_khugepaged)
    (process_running process_irq_9-acpi)
    (process_running process_irq_95-nvidia)
    (process_running process_nvidia_1)
    (process_running process_nv_queue_1)
    (process_running process_oddjobd)
    (process_running process_tailscaled)
    (process_running process_unattended-upgr)
    (process_running process_anydesk)
    (process_running process_containerd)
    (process_running process_sshd)
    (process_running process_xrdp-sesman)
    (process_running process_irq_30-dmar4-prq)
    (process_running process_kswapd0)
    (process_running process_ecryptfs-kthread)
    (process_running process_hwrng)
    (process_running process_gdm3)
    (process_running process_uvm_global_queue)
    (process_running process_uvm_deferred_release_queue)
    (process_running process_uvm_tools_event_queue)
    (process_running process_upowerd)
    (process_running process_kthreadd)
    (process_running process_pycharm)
    (process_running process_cef_server)
    (process_running process_nvidia-drm_timeline-4b)
    (process_running process_nvidia-drm_timeline-4c)
    (process_running process_dockerd)
    (process_running process_kerneloops)
    (process_running process_kerneloops_1)
    (process_running process_snapd)
    (process_running process_osqueryd)
    (process_running process_osqueryd_1)
    (process_running process_psimon)
    (process_running process_irq_59-enp1s0)
    (process_running process_master)
    (process_running process_scsi_eh_0)
    (process_running process_scsi_eh_1)
    (process_running process_scsi_eh_2)
    (process_running process_scsi_eh_3)
    (process_running process_containerd-shim)
    (process_running process_containerd-shim_1)
    (process_running process_scsi_eh_4)
    (process_running process_scsi_eh_5)
    (process_running process_node)
    (process_running process_startup_sh)
    (process_running process_pool_workqueue_release)
    (process_running process_scsi_eh_6)
    (process_running process_scsi_eh_7)
    (process_running process_cupsd)
    (process_running process_cups-browsed)
    (process_running process_docker-proxy)
    (process_running process_docker-proxy_1)
    (process_running process_scsi_eh_8)
    (process_running process_usb-storage)
    (process_running process_jbd2_sda-8)
    (process_running process_irq_62-pciehp)
    (process_running process_docker-proxy_2)
    (process_running process_docker-proxy_3)
    (process_running process_ollama)
    (process_running process_jbd2_nvme0n1p4-8)
    (process_running process_systemd-journal)
    (process_running process_fwupd)
    (process_running process_systemd-udevd)
    (process_running process_psimon_1)
    (process_running process_gdm-session-wor)
    (process_running process_systemd_1)
    (process_running process_nvidia-drm_timeline-37)
    (process_running process_nvidia-drm_timeline-38)
    (process_running process_irq_83-mei_me)
    (process_running process_irq_84-idxd-misc)
    (process_running process_jbd2_nvme0n1p1-8)
    (process_running process_auditd)
    (process_running process_audit_prune_tree)
    (process_running process_nv_queue_2)
    (process_running process_nv_queue_3)
    (process_running process_nv_open_q)
    (process_running process_nv_open_q_1)
    (process_running process_networkd-dispat)
    (process_running process_incrond)
    (process_running process_power-profiles-)
    (process_running process_sssd)
    (process_running process_switcheroo-cont)
    (process_running process_udisksd)
    (port_open port_6_6188)
    (port_open port_6_631)
    (port_open port_6_53)
    (port_open port_6_11434)
    (port_open port_6_7070)
    (port_open port_6_3000)
    (port_open port_6_25)
    (port_open port_6_22)
    (port_open port_6_11436)
    (port_open port_6_6189)
    (port_open port_6_3350)
    (port_open port_6_3389)
    (port_open port_6_63342)
    (port_open port_17_53)
    (port_open port_17_5353)
    (port_open port_255_58)
    (port_open port_0_0)
    (port_open port_2054_0)
    (service_exists service_wpa_supplicant_service)
    (service_running service_wpa_supplicant_service)
    (service_enabled service_wpa_supplicant_service)
    (service_exists service_systemd-tmpfiles-clean_service)
    (service_enabled service_systemd-tmpfiles-clean_service)
    (service_exists service_anydesk_service)
    (service_running service_anydesk_service)
    (service_enabled service_anydesk_service)
    (service_exists service_systemd-repart_service)
    (service_enabled service_systemd-repart_service)
    (service_exists service_systemd-networkd-wait-online_service)
    (service_enabled service_systemd-networkd-wait-online_service)
    (service_exists service_systemd-backlight_backlight_nvidia_0_service)
    (service_enabled service_systemd-backlight_backlight_nvidia_0_service)
    (service_exists service_systemd-ask-password-wall_service)
    (service_enabled service_systemd-ask-password-wall_service)
    (service_exists service_systemd-journald_service)
    (service_running service_systemd-journald_service)
    (service_enabled service_systemd-journald_service)
    (service_exists service_systemd-journal-flush_service)
    (service_running service_systemd-journal-flush_service)
    (service_enabled service_systemd-journal-flush_service)
    (service_exists service_rsyslog_service)
    (service_running service_rsyslog_service)
    (service_enabled service_rsyslog_service)
    (service_exists service_cups-browsed_service)
    (service_running service_cups-browsed_service)
    (service_enabled service_cups-browsed_service)
    (service_exists service_kerneloops_service)
    (service_running service_kerneloops_service)
    (service_enabled service_kerneloops_service)
    (service_exists service_osqueryd_service)
    (service_running service_osqueryd_service)
    (service_enabled service_osqueryd_service)
    (service_exists service_keyboard-setup_service)
    (service_running service_keyboard-setup_service)
    (service_enabled service_keyboard-setup_service)
    (service_exists service_systemd-pcrphase_service)
    (service_enabled service_systemd-pcrphase_service)
    (service_exists service_systemd-tmpfiles-setup-dev-early_service)
    (service_running service_systemd-tmpfiles-setup-dev-early_service)
    (service_enabled service_systemd-tmpfiles-setup-dev-early_service)
    (service_exists service_systemd-resolved_service)
    (service_running service_systemd-resolved_service)
    (service_enabled service_systemd-resolved_service)
    (service_exists service_sssd_service)
    (service_running service_sssd_service)
    (service_enabled service_sssd_service)
    (service_exists service_systemd-user-sessions_service)
    (service_running service_systemd-user-sessions_service)
    (service_enabled service_systemd-user-sessions_service)
    (service_exists service_alsa-restore_service)
    (service_running service_alsa-restore_service)
    (service_enabled service_alsa-restore_service)
    (service_exists service_plymouth-quit-wait_service)
    (service_running service_plymouth-quit-wait_service)
    (service_enabled service_plymouth-quit-wait_service)
    (service_exists service_sssd-pam_service)
    (service_enabled service_sssd-pam_service)
    (service_exists service_nvidia-persistenced_service)
    (service_running service_nvidia-persistenced_service)
    (service_enabled service_nvidia-persistenced_service)
    (service_exists service_systemd-fsck_dev-disk-by_x2duuid-f84e_x2dead2_service)
    (service_running service_systemd-fsck_dev-disk-by_x2duuid-f84e_x2dead2_service)
    (service_enabled service_systemd-fsck_dev-disk-by_x2duuid-f84e_x2dead2_service)
    (service_exists service_plymouth-read-write_service)
    (service_running service_plymouth-read-write_service)
    (service_enabled service_plymouth-read-write_service)
    (service_exists service_ssh_service)
    (service_running service_ssh_service)
    (service_enabled service_ssh_service)
    (service_exists service_openvpn_service)
    (service_running service_openvpn_service)
    (service_enabled service_openvpn_service)
    (service_exists service_snapd_seeded_service)
    (service_running service_snapd_seeded_service)
    (service_enabled service_snapd_seeded_service)
    (service_exists service_systemd-sysext_service)
    (service_enabled service_systemd-sysext_service)
    (service_exists service_systemd-logind_service)
    (service_running service_systemd-logind_service)
    (service_enabled service_systemd-logind_service)
    (service_exists service_systemd-rfkill_service)
    (service_enabled service_systemd-rfkill_service)
    (service_exists service_snapd_apparmor_service)
    (service_running service_snapd_apparmor_service)
    (service_enabled service_snapd_apparmor_service)
    (service_exists service_sssd-autofs_service)
    (service_enabled service_sssd-autofs_service)
    (service_exists service_dbus_service)
    (service_running service_dbus_service)
    (service_enabled service_dbus_service)
    (service_exists service_systemd-udevd_service)
    (service_running service_systemd-udevd_service)
    (service_enabled service_systemd-udevd_service)
    (service_exists service_upower_service)
    (service_running service_upower_service)
    (service_enabled service_upower_service)
    (service_exists service_systemd-suspend_service)
    (service_enabled service_systemd-suspend_service)
    (service_exists service_postfix_service)
    (service_running service_postfix_service)
    (service_enabled service_postfix_service)
    (service_exists service_systemd-initctl_service)
    (service_enabled service_systemd-initctl_service)
    (service_exists service_systemd-sysctl_service)
    (service_running service_systemd-sysctl_service)
    (service_enabled service_systemd-sysctl_service)
    (service_exists service_modemmanager_service)
    (service_running service_modemmanager_service)
    (service_enabled service_modemmanager_service)
    (service_exists service_systemd-tpm2-setup_service)
    (service_enabled service_systemd-tpm2-setup_service)
    (service_exists service_user-runtime-dir_114505204_service)
    (service_running service_user-runtime-dir_114505204_service)
    (service_enabled service_user-runtime-dir_114505204_service)
    (service_exists service_systemd-modules-load_service)
    (service_running service_systemd-modules-load_service)
    (service_enabled service_systemd-modules-load_service)
    (service_exists service_networkmanager-wait-online_service)
    (service_running service_networkmanager-wait-online_service)
    (service_enabled service_networkmanager-wait-online_service)
    (service_exists service_systemd-vconsole-setup_service)
    (service_exists service_systemd-tmpfiles-setup-dev_service)
    (service_running service_systemd-tmpfiles-setup-dev_service)
    (service_enabled service_systemd-tmpfiles-setup-dev_service)
    (service_exists service_systemd-fsckd_service)
    (service_enabled service_systemd-fsckd_service)
    (service_exists service_networkmanager_service)
    (service_running service_networkmanager_service)
    (service_enabled service_networkmanager_service)
    (service_exists service_xrdp-sesman_service)
    (service_running service_xrdp-sesman_service)
    (service_enabled service_xrdp-sesman_service)
    (service_exists service_snapd_core-fixup_service)
    (service_enabled service_snapd_core-fixup_service)
    (service_exists service_systemd-firstboot_service)
    (service_enabled service_systemd-firstboot_service)
    (service_exists service_gdm_service)
    (service_running service_gdm_service)
    (service_enabled service_gdm_service)
    (service_exists service_snapd_system-shutdown_service)
    (service_enabled service_snapd_system-shutdown_service)
    (service_exists service_systemd-pcrphase-sysinit_service)
    (service_enabled service_systemd-pcrphase-sysinit_service)
    (service_exists service_systemd-pstore_service)
    (service_enabled service_systemd-pstore_service)
    (service_exists service_postfix_-_service)
    (service_running service_postfix_-_service)
    (service_enabled service_postfix_-_service)
    (service_exists service_incron_service)
    (service_running service_incron_service)
    (service_enabled service_incron_service)
    (service_exists service_systemd-tpm2-setup-early_service)
    (service_enabled service_systemd-tpm2-setup-early_service)
    (service_exists service_ollama_service)
    (service_running service_ollama_service)
    (service_enabled service_ollama_service)
    (service_exists service_systemd-suspend-then-hibernate_service)
    (service_enabled service_systemd-suspend-then-hibernate_service)
    (service_exists service_systemd-soft-reboot_service)
    (service_enabled service_systemd-soft-reboot_service)
    (service_exists service_accounts-daemon_service)
    (service_running service_accounts-daemon_service)
    (service_enabled service_accounts-daemon_service)
    (service_exists service_systemd-hibernate_service)
    (service_enabled service_systemd-hibernate_service)
    (service_exists service_colord_service)
    (service_running service_colord_service)
    (service_enabled service_colord_service)
    (service_exists service_plymouth-start_service)
    (service_running service_plymouth-start_service)
    (service_enabled service_plymouth-start_service)
    (service_exists service_systemd-ask-password-plymouth_service)
    (service_enabled service_systemd-ask-password-plymouth_service)
    (service_exists service_lm-sensors_service)
    (service_running service_lm-sensors_service)
    (service_enabled service_lm-sensors_service)
    (service_exists service_systemd-binfmt_service)
    (service_running service_systemd-binfmt_service)
    (service_enabled service_systemd-binfmt_service)
    (service_exists service_systemd-udev-settle_service)
    (service_enabled service_systemd-udev-settle_service)
    (service_exists service_systemd-networkd_service)
    (service_enabled service_systemd-networkd_service)
    (service_exists service_sysstat-summary_service)
    (service_enabled service_sysstat-summary_service)
    (service_exists service_oddjobd_service)
    (service_running service_oddjobd_service)
    (service_enabled service_oddjobd_service)
    (service_exists service_fwupd_service)
    (service_running service_fwupd_service)
    (service_enabled service_fwupd_service)
    (service_exists service_systemd-hwdb-update_service)
    (service_enabled service_systemd-hwdb-update_service)
    (service_exists service_sysstat-collect_service)
    (service_enabled service_sysstat-collect_service)
    (service_exists service_systemd-quotacheck_service)
    (service_enabled service_systemd-quotacheck_service)
    (service_exists service_sssd-pac_service)
    (service_failed service_sssd-pac_service)
    (service_enabled service_sssd-pac_service)
    (service_exists service_sssd-nss_service)
    (service_enabled service_sssd-nss_service)
    (service_exists service_systemd-hibernate-resume_service)
    (service_enabled service_systemd-hibernate-resume_service)
    (service_exists service_snapd_autoimport_service)
    (service_enabled service_snapd_autoimport_service)
    (service_exists service_power-profiles-daemon_service)
    (service_running service_power-profiles-daemon_service)
    (service_enabled service_power-profiles-daemon_service)
    (service_exists service_snapd_recovery-chooser-trigger_service)
    (service_enabled service_snapd_recovery-chooser-trigger_service)
    (service_exists service_systemd-udev-trigger_service)
    (service_running service_systemd-udev-trigger_service)
    (service_enabled service_systemd-udev-trigger_service)
    (service_exists service_snapd_service)
    (service_running service_snapd_service)
    (service_enabled service_snapd_service)
    (service_exists service_systemd-oomd_service)
    (service_running service_systemd-oomd_service)
    (service_enabled service_systemd-oomd_service)
    (service_exists service_ubuntu-fan_service)
    (service_running service_ubuntu-fan_service)
    (service_enabled service_ubuntu-fan_service)
    (service_exists service_plymouth-quit_service)
    (service_enabled service_plymouth-quit_service)
    (service_exists service_sssd-sudo_service)
    (service_enabled service_sssd-sudo_service)
    (service_exists service_systemd-pcrmachine_service)
    (service_enabled service_systemd-pcrmachine_service)
    (service_exists service_systemd-update-utmp-runlevel_service)
    (service_enabled service_systemd-update-utmp-runlevel_service)
    (service_exists service_apparmor_service)
    (service_running service_apparmor_service)
    (service_enabled service_apparmor_service)
    (service_exists service_systemd-battery-check_service)
    (service_enabled service_systemd-battery-check_service)
    (service_exists service_avahi-daemon_service)
    (service_running service_avahi-daemon_service)
    (service_enabled service_avahi-daemon_service)
    (service_exists service_cron_service)
    (service_running service_cron_service)
    (service_enabled service_cron_service)
    (service_exists service_gnome-remote-desktop_service)
    (service_running service_gnome-remote-desktop_service)
    (service_enabled service_gnome-remote-desktop_service)
    (service_exists service_systemd-journal-catalog-update_service)
    (service_enabled service_systemd-journal-catalog-update_service)
    (service_exists service_xrdp_service)
    (service_running service_xrdp_service)
    (service_enabled service_xrdp_service)
    (service_exists service_auditd_service)
    (service_running service_auditd_service)
    (service_enabled service_auditd_service)
    (service_exists service_udisks2_service)
    (service_running service_udisks2_service)
    (service_enabled service_udisks2_service)
    (service_exists service_systemd-timesyncd_service)
    (service_running service_systemd-timesyncd_service)
    (service_enabled service_systemd-timesyncd_service)
    (service_exists service_systemd-bsod_service)
    (service_enabled service_systemd-bsod_service)
    (service_exists service_systemd-remount-fs_service)
    (service_running service_systemd-remount-fs_service)
    (service_enabled service_systemd-remount-fs_service)
    (service_exists service_systemd-random-seed_service)
    (service_running service_systemd-random-seed_service)
    (service_enabled service_systemd-random-seed_service)
    (service_exists service_switcheroo-control_service)
    (service_running service_switcheroo-control_service)
    (service_enabled service_switcheroo-control_service)
    (service_exists service_tailscaled_service)
    (service_running service_tailscaled_service)
    (service_enabled service_tailscaled_service)
    (service_exists service_console-setup_service)
    (service_running service_console-setup_service)
    (service_enabled service_console-setup_service)
    (service_exists service_cups_service)
    (service_running service_cups_service)
    (service_enabled service_cups_service)
    (service_exists service_plymouth-switch-root_service)
    (service_enabled service_plymouth-switch-root_service)
    (service_exists service_sysstat_service)
    (service_running service_sysstat_service)
    (service_enabled service_sysstat_service)
    (service_exists service_fwupd-refresh_service)
    (service_enabled service_fwupd-refresh_service)
    (service_exists service_systemd-fsck_dev-disk-by_x2duuid-494638c4_x2d4d70_x2d4d12_x2db520_x2d52bfb646ce41_service)
    (service_running service_systemd-fsck_dev-disk-by_x2duuid-494638c4_x2d4d70_x2d4d12_x2db520_x2d52bfb646ce41_service)
    (service_enabled service_systemd-fsck_dev-disk-by_x2duuid-494638c4_x2d4d70_x2d4d12_x2db520_x2d52bfb646ce41_service)
    (service_exists service_setvtrgb_service)
    (service_running service_setvtrgb_service)
    (service_enabled service_setvtrgb_service)
    (service_exists service_apport-autoreport_service)
    (service_enabled service_apport-autoreport_service)
    (service_exists service_networkd-dispatcher_service)
    (service_running service_networkd-dispatcher_service)
    (service_enabled service_networkd-dispatcher_service)
    (service_exists service_snapd_snap-repair_service)
    (service_enabled service_snapd_snap-repair_service)
    (service_exists service_systemd-tmpfiles-setup_service)
    (service_running service_systemd-tmpfiles-setup_service)
    (service_enabled service_systemd-tmpfiles-setup_service)
    (service_exists service_snapd_failure_service)
    (service_enabled service_snapd_failure_service)
    (service_exists service_kmod-static-nodes_service)
    (service_running service_kmod-static-nodes_service)
    (service_enabled service_kmod-static-nodes_service)
    (service_exists service_systemd-hybrid-sleep_service)
    (service_enabled service_systemd-hybrid-sleep_service)
    (service_exists service_systemd-ask-password-console_service)
    (service_enabled service_systemd-ask-password-console_service)
    (service_exists service_unattended-upgrades_service)
    (service_running service_unattended-upgrades_service)
    (service_enabled service_unattended-upgrades_service)
    (service_exists service_user_114505204_service)
    (service_running service_user_114505204_service)
    (service_enabled service_user_114505204_service)
    (service_exists service_systemd-pcrphase-initrd_service)
    (service_enabled service_systemd-pcrphase-initrd_service)
    (service_exists service_containerd_service)
    (service_running service_containerd_service)
    (service_enabled service_containerd_service)
    (service_exists service_systemd-sysusers_service)
    (service_enabled service_systemd-sysusers_service)
    (service_exists service_apport_service)
    (service_running service_apport_service)
    (service_enabled service_apport_service)
    (service_exists service_systemd-update-done_service)
    (service_enabled service_systemd-update-done_service)
    (service_exists service_docker_service)
    (service_running service_docker_service)
    (service_enabled service_docker_service)
    (service_exists service_systemd-update-utmp_service)
    (service_running service_systemd-update-utmp_service)
    (service_enabled service_systemd-update-utmp_service)
    (service_exists service_systemd-machine-id-commit_service)
    (service_enabled service_systemd-machine-id-commit_service)
    (service_exists service_polkit_service)
    (service_running service_polkit_service)
    (service_enabled service_polkit_service)
    (service_exists service_rtkit-daemon_service)
    (service_running service_rtkit-daemon_service)
    (service_enabled service_rtkit-daemon_service)
    (service_exists service_sssd-ssh_service)
    (service_enabled service_sssd-ssh_service)
    (service_exists service_systemd-fsck-root_service)
    (service_enabled service_systemd-fsck-root_service)
    (package_installed package_anydesk)
    (package_installed package_apparmor)
    (package_installed package_apport)
    (package_installed package_auditd)
    (package_installed package_avahi-daemon)
    (package_installed package_colord)
    (package_installed package_console-setup)
    (package_installed package_containerd)
    (package_installed package_cron)
    (package_installed package_cups)
    (package_installed package_cups-browsed)
    (package_installed package_dbus)
    (package_installed package_docker_io)
    (package_installed package_fwupd)
    (package_installed package_gdm3)
    (package_installed package_gnome-remote-desktop)
    (package_installed package_incron)
    (package_installed package_kerneloops)
    (package_installed package_kmod)
    (package_installed package_lm-sensors)
    (package_installed package_networkd-dispatcher)
    (package_installed package_oddjob)
    (package_installed package_openvpn)
    (package_installed package_osquery)
    (package_installed package_plymouth)
    (package_installed package_polkitd)
    (package_installed package_postfix)
    (package_installed package_power-profiles-daemon)
    (package_installed package_rsyslog)
    (package_installed package_rtkit)
    (package_installed package_snapd)
    (package_installed package_ssh-import-id)
    (package_installed package_sssd)
    (package_installed package_switcheroo-control)
    (package_installed package_sysstat)
    (package_installed package_systemd)
    (package_installed package_systemd-oomd)
    (package_installed package_systemd-resolved)
    (package_installed package_systemd-timesyncd)
    (package_installed package_tailscale)
    (package_installed package_ubuntu-fan)
    (package_installed package_udisks2)
    (package_installed package_unattended-upgrades)
    (package_installed package_upower)
    (package_installed package_xrdp)
    (file_exists configuration_file__etc_incron_conf)
    (file_exists configuration_file__etc_kerneloops_conf)
    (file_exists configuration_file__etc_oddjobd_conf)
    (file_exists configuration_file__etc_rsyslog_conf)
    (depends_on service_systemd-tmpfiles-clean_service package_systemd)
    (depends_on service_anydesk_service package_anydesk)
    (depends_on service_systemd-repart_service package_systemd)
    (depends_on service_systemd-networkd-wait-online_service package_systemd)
    (depends_on service_systemd-backlight_backlight_nvidia_0_service package_systemd)
    (depends_on service_systemd-ask-password-wall_service package_systemd)
    (depends_on service_systemd-journald_service package_systemd)
    (depends_on service_systemd-journal-flush_service package_systemd)
    (depends_on service_rsyslog_service package_rsyslog)
    (depends_on service_cups-browsed_service package_cups-browsed)
    (depends_on service_kerneloops_service package_kerneloops)
    (depends_on service_osqueryd_service package_osquery)
    (depends_on service_systemd-pcrphase_service package_systemd)
    (depends_on service_systemd-tmpfiles-setup-dev-early_service package_systemd)
    (depends_on service_systemd-resolved_service package_systemd-resolved)
    (depends_on service_sssd_service package_sssd)
    (depends_on service_systemd-user-sessions_service package_systemd)
    (depends_on service_plymouth-quit-wait_service package_plymouth)
    (depends_on service_sssd-pam_service package_sssd)
    (depends_on service_systemd-fsck_dev-disk-by_x2duuid-f84e_x2dead2_service package_systemd)
    (depends_on service_plymouth-read-write_service package_plymouth)
    (depends_on service_ssh_service package_ssh-import-id)
    (depends_on service_openvpn_service package_openvpn)
    (depends_on service_snapd_seeded_service package_snapd)
    (depends_on service_systemd-sysext_service package_systemd)
    (depends_on service_systemd-logind_service package_systemd)
    (depends_on service_systemd-rfkill_service package_systemd)
    (depends_on service_snapd_apparmor_service package_snapd)
    (depends_on service_sssd-autofs_service package_sssd)
    (depends_on service_dbus_service package_dbus)
    (depends_on service_systemd-udevd_service package_systemd)
    (depends_on service_upower_service package_upower)
    (depends_on service_systemd-suspend_service package_systemd)
    (depends_on service_postfix_service package_postfix)
    (depends_on service_systemd-initctl_service package_systemd)
    (depends_on service_systemd-sysctl_service package_systemd)
    (depends_on service_systemd-tpm2-setup_service package_systemd)
    (depends_on service_systemd-modules-load_service package_systemd)
    (depends_on service_systemd-vconsole-setup_service package_systemd)
    (depends_on service_systemd-tmpfiles-setup-dev_service package_systemd)
    (depends_on service_systemd-fsckd_service package_systemd)
    (depends_on service_xrdp-sesman_service package_xrdp)
    (depends_on service_snapd_core-fixup_service package_snapd)
    (depends_on service_systemd-firstboot_service package_systemd)
    (depends_on service_gdm_service package_gdm3)
    (depends_on service_snapd_system-shutdown_service package_snapd)
    (depends_on service_systemd-pcrphase-sysinit_service package_systemd)
    (depends_on service_systemd-pstore_service package_systemd)
    (depends_on service_postfix_-_service package_postfix)
    (depends_on service_incron_service package_incron)
    (depends_on service_systemd-tpm2-setup-early_service package_systemd)
    (depends_on service_systemd-suspend-then-hibernate_service package_systemd)
    (depends_on service_systemd-soft-reboot_service package_systemd)
    (depends_on service_systemd-hibernate_service package_systemd)
    (depends_on service_colord_service package_colord)
    (depends_on service_plymouth-start_service package_plymouth)
    (depends_on service_systemd-ask-password-plymouth_service package_systemd)
    (depends_on service_lm-sensors_service package_lm-sensors)
    (depends_on service_systemd-binfmt_service package_systemd)
    (depends_on service_systemd-udev-settle_service package_systemd)
    (depends_on service_systemd-networkd_service package_systemd)
    (depends_on service_sysstat-summary_service package_sysstat)
    (depends_on service_oddjobd_service package_oddjob)
    (depends_on service_fwupd_service package_fwupd)
    (depends_on service_systemd-hwdb-update_service package_systemd)
    (depends_on service_sysstat-collect_service package_sysstat)
    (depends_on service_systemd-quotacheck_service package_systemd)
    (depends_on service_sssd-pac_service package_sssd)
    (depends_on service_sssd-nss_service package_sssd)
    (depends_on service_systemd-hibernate-resume_service package_systemd)
    (depends_on service_snapd_autoimport_service package_snapd)
    (depends_on service_power-profiles-daemon_service package_power-profiles-daemon)
    (depends_on service_snapd_recovery-chooser-trigger_service package_snapd)
    (depends_on service_systemd-udev-trigger_service package_systemd)
    (depends_on service_snapd_service package_snapd)
    (depends_on service_systemd-oomd_service package_systemd-oomd)
    (depends_on service_ubuntu-fan_service package_ubuntu-fan)
    (depends_on service_plymouth-quit_service package_plymouth)
    (depends_on service_sssd-sudo_service package_sssd)
    (depends_on service_systemd-pcrmachine_service package_systemd)
    (depends_on service_systemd-update-utmp-runlevel_service package_systemd)
    (depends_on service_apparmor_service package_apparmor)
    (depends_on service_systemd-battery-check_service package_systemd)
    (depends_on service_avahi-daemon_service package_avahi-daemon)
    (depends_on service_cron_service package_cron)
    (depends_on service_gnome-remote-desktop_service package_gnome-remote-desktop)
    (depends_on service_systemd-journal-catalog-update_service package_systemd)
    (depends_on service_xrdp_service package_xrdp)
    (depends_on service_auditd_service package_auditd)
    (depends_on service_udisks2_service package_udisks2)
    (depends_on service_systemd-timesyncd_service package_systemd-timesyncd)
    (depends_on service_systemd-bsod_service package_systemd)
    (depends_on service_systemd-remount-fs_service package_systemd)
    (depends_on service_systemd-random-seed_service package_systemd)
    (depends_on service_switcheroo-control_service package_switcheroo-control)
    (depends_on service_tailscaled_service package_tailscale)
    (depends_on service_console-setup_service package_console-setup)
    (depends_on service_cups_service package_cups)
    (depends_on service_plymouth-switch-root_service package_plymouth)
    (depends_on service_sysstat_service package_sysstat)
    (depends_on service_fwupd-refresh_service package_fwupd)
    (depends_on service_systemd-fsck_dev-disk-by_x2duuid-494638c4_x2d4d70_x2d4d12_x2db520_x2d52bfb646ce41_service package_systemd)
    (depends_on service_apport-autoreport_service package_apport)
    (depends_on service_networkd-dispatcher_service package_networkd-dispatcher)
    (depends_on service_snapd_snap-repair_service package_snapd)
    (depends_on service_systemd-tmpfiles-setup_service package_systemd)
    (depends_on service_snapd_failure_service package_snapd)
    (depends_on service_kmod-static-nodes_service package_kmod)
    (depends_on service_systemd-hybrid-sleep_service package_systemd)
    (depends_on service_systemd-ask-password-console_service package_systemd)
    (depends_on service_unattended-upgrades_service package_unattended-upgrades)
    (depends_on service_systemd-pcrphase-initrd_service package_systemd)
    (depends_on service_containerd_service package_containerd)
    (depends_on service_systemd-sysusers_service package_systemd)
    (depends_on service_apport_service package_apport)
    (depends_on service_systemd-update-done_service package_systemd)
    (depends_on service_docker_service package_docker_io)
    (depends_on service_systemd-update-utmp_service package_systemd)
    (depends_on service_systemd-machine-id-commit_service package_systemd)
    (depends_on service_polkit_service package_polkitd)
    (depends_on service_rtkit-daemon_service package_rtkit)
    (depends_on service_sssd-ssh_service package_sssd)
    (depends_on service_systemd-fsck-root_service package_systemd)
    (configures configuration_file__etc_rsyslog_conf service_rsyslog_service)
    (configures configuration_file__etc_kerneloops_conf service_kerneloops_service)
    (configures configuration_file__etc_incron_conf service_incron_service)
    (configures configuration_file__etc_oddjobd_conf service_oddjobd_service)
    (configures configuration_file__etc_incron_conf service_cron_service)
    (member_of user_root group_root)
    (member_of user_sync group_nogroup)
    (member_of user__apt group_nogroup)
    (member_of user_nobody group_nogroup)
    (member_of user_dhcpcd group_nogroup)
    (member_of user_syslog group_syslog)
    (member_of user_syslog group_adm)
    (member_of user_usbmux group_plugdev)
    (member_of user_kernoops group_nogroup)
    (member_of user_dnsmasq group_nogroup)
    (member_of user_cups-pk-helper group_lpadmin)
    (member_of user_cups-browsed group_lpadmin)
    (member_of user_gnome-initial-setup group_nogroup)
    (member_of user_administrator group_administrator)
    (member_of user_administrator group_adm)
    (member_of user_administrator group_cdrom)
    (member_of user_administrator group_sudo)
    (member_of user_administrator group_dip)
    (member_of user_administrator group_plugdev)
    (member_of user_administrator group_users)
    (member_of user_administrator group_lpadmin)
    (member_of user_sshd group_nogroup)
    (member_of user_emmanuelli group_emmanuelli)
    (member_of user_emmanuelli group_users)
    (can_escalate user_administrator)
    (network_available)
  )

  (:goal
    (and
      (network_available)
    )
  )
)