(define (problem sysadmin-initial)
  (:domain sysadmin)

  (:objects
    user_root user_sync user_nobody user_syslog user__apt user_usbmux user_dnsmasq user_kernoops user_cups-pk-helper user_gnome-initial-setup user_resbears user_ollama - user
    group_root group_adm group_cdrom group_sudo group_dip group_video group_plugdev group_nogroup group_render group_syslog group_lpadmin group_lxd group_resbears group_sambashare group_ollama group_docker - group
    process_systemd process_vmware-vmblock- process_irq_16-vmwgfx process_systemd-udevd process_gvfsd-http process_firefox process_crashhelper process_forkserver process_socket_process process_isolated_web_co process_rdd_process process_webextensions process_utility_process process_isolated_web_co process_isolated_web_co process_web_content process_privileged_cont process_web_content process_web_content process_snapd process_bash process_irq_35-vmw_vmci process_irq_36-vmw_vmci process_irq_37-vmw_vmci process_sleep process_uv process_python3 process_osqueryi process_vgauthservice process_vmtoolsd process_nv_queue process_nv_queue process_nv_open_q process_acpid process_networkmanager process_irqbalance process_networkd-dispat process_polkitd process_power-profiles- process_rsyslogd process_accounts-daemon process_cron process_switcheroo-cont process_nv_open_q process_systemd-logind process_udisksd process_wpa_supplicant process_modemmanager process_canonical-livep process_containerd process_unattended-upgr process_nvidia-modeset_kthread_q process_nvidia-modeset_deferred_close_kthread_q process_irq_38-nvidia process_irq_39-nvidia process_irq_40-nvidia process_irq_41-nvidia process_irq_42-nvidia process_irq_43-nvidia process_nvidia process_nv_queue process_ollama process_kerneloops process_kerneloops process_kthreadd process_dockerd process_irq_44-nvidia process_irq_45-nvidia process_irq_46-nvidia process_irq_47-nvidia process_irq_48-nvidia process_irq_49-nvidia process_nvidia process_nv_queue process_docker-proxy process_docker-proxy process_containerd-shim process_python3 process_uvm_global_queue process_uvm_deferred_release_queue process_uvm_tools_event_queue process_gdm3 process_java process_gdm-session-wor process_systemd process__sd-pam_ process_pipewire process_pipewire-media- process_pulseaudio process_pool_workqueue_release process_gnome-keyring-d process_gdm-x-session process_xorg process_dbus-daemon process_xdg-document-po process_xdg-permission- process_fusermount3 process_ollama process_gnome-session-b process_at-spi-bus-laun process_dbus-daemon process_getmachineid_sh process_gnome-session-c process_gvfsd process_gvfsd-fuse process_gnome-session-b process_gnome-shell process_desktopdaemon process_blastserver process_snapd-desktop-i process_snapd-desktop-i process_gnome-shell-cal process_evolution-sourc process_upowerd process_goa-daemon process_dconf-service process_gvfs-udisks2-vo process_evolution-calen process_gvfs-goa-volume process_goa-identity-se process_gvfs-afc-volume process_evolution-addre process_gvfs-gphoto2-vo process_gvfs-mtp-volume process_packagekitd process_gvfsd-trash process_gjs process_at-spi2-registr process_kdevtmpfs process_sh process_gsd-a11y-settin process_ibus-daemon process_gsd-color process_gsd-datetime process_gsd-housekeepin process_gsd-keyboard process_gsd-media-keys process_kauditd process_gsd-power process_gsd-print-notif process_gsd-rfkill process_gsd-screensaver process_gsd-sharing process_gsd-smartcard process_gsd-sound process_gsd-wacom process_khungtaskd process_gsd-xsettings process_xdg-desktop-por process_oom_reaper process_vmtoolsd process_evolution-alarm process_gsd-disk-utilit process_kcompactd0 process_fdm process_kcompactd1 process_ibus-memconf process_ibus-extension- process_ksmd process_xdg-desktop-por process_gsd-printer process_ibus-x11 process_ibus-portal process_khugepaged process_irq_9-acpi process_gjs process_tracker-miner-f process_ibus-engine-sim process_xdg-desktop-por process_kswapd0 process_kswapd1 process_ecryptfs-kthread process_scsi_eh_0 process_gjs process_scsi_eh_1 process_gvfsd-metadata process_jetbrains-toolb process_cupsd process_cups-browsed process_snap process_update-notifier process_scsi_eh_2 process_scsi_eh_3 process_scsi_eh_4 process_scsi_eh_5 process_scsi_eh_6 process_scsi_eh_7 process_scsi_eh_8 process_scsi_eh_9 process_scsi_eh_10 process_scsi_eh_11 process_scsi_eh_12 process_scsi_eh_13 process_scsi_eh_14 process_scsi_eh_15 process_scsi_eh_16 process_scsi_eh_17 process_scsi_eh_18 process_scsi_eh_19 process_scsi_eh_20 process_scsi_eh_21 process_scsi_eh_22 process_scsi_eh_23 process_scsi_eh_24 process_scsi_eh_25 process_scsi_eh_26 process_scsi_eh_27 process_scsi_eh_28 process_scsi_eh_29 process_scsi_eh_30 process_scsi_eh_31 process_scsi_eh_32 process_gnome-calendar process_pycharm process_fsnotifier process_cef_server process_cef_server process_cef_server process_cef_server process_cef_server process_cef_server process_embeddings-serv process_cef_server process_cef_server process_bash process_osqueryd process_osqueryd process_jbd2_sda2-8 process_systemd-journal - process
    port_6_631 port_6_6188 port_6_3000 port_6_53 port_6_6189 port_6_52829 port_6_11434 port_6_63342 port_6_34167 port_6_37291 port_17_53 port_17_5353 port_255_58 port_0_0 port_2054_0 - port
    service_open-vm-tools_service service_acpid_service service_setvtrgb_service service_systemd-oomd_service service_apparmor_service service_systemd-machine-id-commit_service service_wpa_supplicant_service service_avahi-daemon_service service_modemmanager_service service_snapd_service service_systemd-tmpfiles-setup_service service_viewagent_shutdown_service service_systemd-sysusers_service service_systemd-update-utmp-runlevel_service service_systemd-ask-password-plymouth_service service_systemd-boot-system-token_service service_systemd-initctl_service service_systemd-remount-fs_service service_snapd_recovery-chooser-trigger_service service_systemd-backlight_backlight_nvidia_0_service service_nvidia-persistenced_service service_gdm_service service_snapd_autoimport_service service_snapd_snap-repair_service service_systemd-pstore_service service_vgauth_service service_systemd-update-utmp_service service_ubuntu-fan_service service_power-profiles-daemon_service service_systemd-fsck-root_service service_ufw_service service_kmod-static-nodes_service service_ollama_service service_plymouth-read-write_service service_cron_service service_openvpn_service service_systemd-binfmt_service service_apport_service service_systemd-logind_service service_plymouth-quit-wait_service service_polkit_service service_plymouth-quit_service service_systemd-udevd_service service_colord_service service_dbus_service service_snap_canonical-livepatch_canonical-livepatchd_service service_snapd_failure_service service_rsyslog_service service_networkd-dispatcher_service service_rtkit-daemon_service service_snapd_apparmor_service service_udisks2_service service_cups_service service_snapd_core-fixup_service service_unattended-upgrades_service service_upower_service service_irqbalance_service service_systemd-random-seed_service service_systemd-user-sessions_service service_packagekit_service service_user-runtime-dir_1000_service service_networkmanager-wait-online_service service_systemd-tmpfiles-setup-dev_service service_user_1000_service service_switcheroo-control_service service_cups-browsed_service service_systemd-fsckd_service service_systemd-modules-load_service service_systemd-networkd_service service_systemd-udev-trigger_service service_kerneloops_service service_containerd_service service_systemd-ask-password-wall_service service_systemd-ask-password-console_service service_systemd-quotacheck_service service_systemd-resolved_service service_networkmanager_service service_systemd-timesyncd_service service_systemd-tmpfiles-clean_service service_viewagent_service service_systemd-sysctl_service service_plymouth-start_service service_systemd-rfkill_service service_snapd_aa-prompt-listener_service service_systemd-journal-flush_service service_keyboard-setup_service service_accounts-daemon_service service_osqueryd_service service_console-setup_service service_systemd-vconsole-setup_service service_systemd-fsck_dev-disk-by_x2duuid-30c8_x2d931f_service service_docker_service service_snapd_seeded_service service_systemd-hwdb-update_service service_apport-autoreport_service service_systemd-update-done_service service_systemd-journald_service - service
    package_acpid package_apparmor package_apport package_avahi-daemon package_colord package_console-setup package_containerd package_cron package_cups package_cups-browsed package_dbus package_docker_io package_gdm3 package_irqbalance package_kerneloops package_kmod package_networkd-dispatcher package_open-vm-tools package_openvpn package_osquery package_packagekit package_plymouth package_polkitd package_power-profiles-daemon package_rsyslog package_rtkit package_snapd package_switcheroo-control package_systemd package_systemd-oomd package_systemd-timesyncd package_ubuntu-fan package_udisks2 package_ufw package_unattended-upgrades package_upower - package
    configuration_file__etc_kerneloops_conf configuration_file__etc_rsyslog_conf - configuration_file
  )

  (:init
    (depends_on service_open-vm-tools_service package_open-vm-tools)
    (depends_on service_acpid_service package_acpid)
    (depends_on service_systemd-oomd_service package_systemd-oomd)
    (depends_on service_apparmor_service package_apparmor)
    (depends_on service_systemd-machine-id-commit_service package_systemd)
    (depends_on service_avahi-daemon_service package_avahi-daemon)
    (depends_on service_snapd_service package_snapd)
    (depends_on service_systemd-tmpfiles-setup_service package_systemd)
    (depends_on service_systemd-sysusers_service package_systemd)
    (depends_on service_systemd-update-utmp-runlevel_service package_systemd)
    (depends_on service_systemd-ask-password-plymouth_service package_systemd)
    (depends_on service_systemd-boot-system-token_service package_systemd)
    (depends_on service_systemd-initctl_service package_systemd)
    (depends_on service_systemd-remount-fs_service package_systemd)
    (depends_on service_snapd_recovery-chooser-trigger_service package_snapd)
    (depends_on service_systemd-backlight_backlight_nvidia_0_service package_systemd)
    (depends_on service_gdm_service package_gdm3)
    (depends_on service_snapd_autoimport_service package_snapd)
    (depends_on service_snapd_snap-repair_service package_snapd)
    (depends_on service_systemd-pstore_service package_systemd)
    (depends_on service_systemd-update-utmp_service package_systemd)
    (depends_on service_ubuntu-fan_service package_ubuntu-fan)
    (depends_on service_power-profiles-daemon_service package_power-profiles-daemon)
    (depends_on service_systemd-fsck-root_service package_systemd)
    (depends_on service_ufw_service package_ufw)
    (depends_on service_kmod-static-nodes_service package_kmod)
    (depends_on service_plymouth-read-write_service package_plymouth)
    (depends_on service_cron_service package_cron)
    (depends_on service_openvpn_service package_openvpn)
    (depends_on service_systemd-binfmt_service package_systemd)
    (depends_on service_apport_service package_apport)
    (depends_on service_systemd-logind_service package_systemd)
    (depends_on service_plymouth-quit-wait_service package_plymouth)
    (depends_on service_polkit_service package_polkitd)
    (depends_on service_plymouth-quit_service package_plymouth)
    (depends_on service_systemd-udevd_service package_systemd)
    (depends_on service_colord_service package_colord)
    (depends_on service_dbus_service package_dbus)
    (depends_on service_snapd_failure_service package_snapd)
    (depends_on service_rsyslog_service package_rsyslog)
    (depends_on service_networkd-dispatcher_service package_networkd-dispatcher)
    (depends_on service_rtkit-daemon_service package_rtkit)
    (depends_on service_snapd_apparmor_service package_snapd)
    (depends_on service_udisks2_service package_udisks2)
    (depends_on service_cups_service package_cups)
    (depends_on service_snapd_core-fixup_service package_snapd)
    (depends_on service_unattended-upgrades_service package_unattended-upgrades)
    (depends_on service_upower_service package_upower)
    (depends_on service_irqbalance_service package_irqbalance)
    (depends_on service_systemd-random-seed_service package_systemd)
    (depends_on service_systemd-user-sessions_service package_systemd)
    (depends_on service_packagekit_service package_packagekit)
    (depends_on service_systemd-tmpfiles-setup-dev_service package_systemd)
    (depends_on service_switcheroo-control_service package_switcheroo-control)
    (depends_on service_cups-browsed_service package_cups-browsed)
    (depends_on service_systemd-fsckd_service package_systemd)
    (depends_on service_systemd-modules-load_service package_systemd)
    (depends_on service_systemd-networkd_service package_systemd)
    (depends_on service_systemd-udev-trigger_service package_systemd)
    (depends_on service_kerneloops_service package_kerneloops)
    (depends_on service_containerd_service package_containerd)
    (depends_on service_systemd-ask-password-wall_service package_systemd)
    (depends_on service_systemd-ask-password-console_service package_systemd)
    (depends_on service_systemd-quotacheck_service package_systemd)
    (depends_on service_systemd-resolved_service package_systemd)
    (depends_on service_systemd-timesyncd_service package_systemd-timesyncd)
    (depends_on service_systemd-tmpfiles-clean_service package_systemd)
    (depends_on service_systemd-sysctl_service package_systemd)
    (depends_on service_plymouth-start_service package_plymouth)
    (depends_on service_systemd-rfkill_service package_systemd)
    (depends_on service_snapd_aa-prompt-listener_service package_snapd)
    (depends_on service_systemd-journal-flush_service package_systemd)
    (depends_on service_osqueryd_service package_osquery)
    (depends_on service_console-setup_service package_console-setup)
    (depends_on service_systemd-vconsole-setup_service package_systemd)
    (depends_on service_systemd-fsck_dev-disk-by_x2duuid-30c8_x2d931f_service package_systemd)
    (depends_on service_docker_service package_docker_io)
    (depends_on service_snapd_seeded_service package_snapd)
    (depends_on service_systemd-hwdb-update_service package_systemd)
    (depends_on service_apport-autoreport_service package_apport)
    (depends_on service_systemd-update-done_service package_systemd)
    (depends_on service_systemd-journald_service package_systemd)
    (configures configuration_file__etc_rsyslog_conf service_rsyslog_service)
    (configures configuration_file__etc_kerneloops_conf service_kerneloops_service)
    (member_of user_root group_root)
    (member_of user_sync group_nogroup)
    (member_of user_nobody group_nogroup)
    (member_of user_syslog group_syslog)
    (member_of user_syslog group_adm)
    (member_of user__apt group_nogroup)
    (member_of user_usbmux group_plugdev)
    (member_of user_dnsmasq group_nogroup)
    (member_of user_kernoops group_nogroup)
    (member_of user_cups-pk-helper group_lpadmin)
    (member_of user_gnome-initial-setup group_nogroup)
    (member_of user_resbears group_resbears)
    (member_of user_resbears group_adm)
    (member_of user_resbears group_cdrom)
    (member_of user_resbears group_sudo)
    (member_of user_resbears group_dip)
    (member_of user_resbears group_plugdev)
    (member_of user_resbears group_lpadmin)
    (member_of user_resbears group_lxd)
    (member_of user_resbears group_sambashare)
    (member_of user_resbears group_ollama)
    (member_of user_resbears group_docker)
    (member_of user_ollama group_ollama)
    (member_of user_ollama group_video)
    (member_of user_ollama group_render)
    (network_available)
  )

  (:goal
    (and
      (network_available)
    )
  )
)