;; =============================================================================
;; SYSADMIN PDDL DOMAIN - Ubuntu 25.10 'Questing Quokka'
;; Auto-generated by Phase 2: Parallel Synthesis (Map-Reduce)
;; =============================================================================

(define (domain sysadmin)

  (:requirements :strips :typing :negative-preconditions)

  ;; Type Hierarchy
  (:types
    filesystem_object firewall_rule group interface package port process repository service user - object
    directory file - filesystem_object
    configuration_file - file
    human_user system_user - user
  )

  ;; Predicates (extracted from action bodies and explicit declarations)
  (:predicates
    (directory_exists ?d - directory)
    (file_exists ?src - service)
    (file_owned_by ?f - file ?u - user)
    (firewall_rule_active ?r - repository)
    (group_exists ?g - group)
    (installed ?p - package)
    (member_of ?u - user ?g - group)
    (network_available)
    (package_available ?p - package)
    (package_installed ?p - package)
    (port_allowed ?p - package)
    (repo_enabled ?r - repository)
    (service_enabled ?s - service)
    (service_exists ?s - service)
    (service_running ?s - service)
    (traffic_blocked ?r - repository)
    (user_exists ?u - user)
    (can_escalate ?u - user)
  )

  ;; Action: add_firewall_rule
  (:action add_firewall_rule
    :parameters (?r - firewall_rule)
    :precondition (and
      (not (firewall_rule_active ?r))
    )
    :effect (and
      (firewall_rule_active ?r)
      (traffic_blocked ?r)
    )
  )

  ;; Action: add_user_to_group
  (:action add_user_to_group
    :parameters (?u - user ?g - group)
    :precondition (and
      (user_exists ?u)
      (group_exists ?g)
      (not (member_of ?u ?g))
    )
    :effect (and
      (member_of ?u ?g)
    )
  )

  ;; Action: change_file_owner
  (:action change_file_owner
    :parameters (?f - file ?u - user)
    :precondition (and
      (file_exists ?f)
      (user_exists ?u)
    )
    :effect (and
      (file_owned_by ?f ?u)
    )
  )

  ;; Action: close_port
  (:action close_port
    :parameters (?p - port)
    :precondition (and
      (port_allowed ?p)
    )
    :effect (and
      (not (port_allowed ?p))
    )
  )

  ;; Action: copy_file
  (:action copy_file
    :parameters (?src - file ?dst - file)
    :precondition (and
      (file_exists ?src)
      (not (file_exists ?dst))
    )
    :effect (and
      (file_exists ?dst)
    )
  )

  ;; Action: create_directory
  (:action create_directory
    :parameters (?d - directory)
    :precondition (and
      (not (directory_exists ?d))
    )
    :effect (and
      (directory_exists ?d)
    )
  )

  ;; Action: create_user
  (:action create_user
    :parameters (?u - user)
    :precondition (and
      (not (user_exists ?u))
    )
    :effect (and
      (user_exists ?u)
    )
  )

  ;; Action: delete_file
  (:action delete_file
    :parameters (?f - file)
    :precondition (and
      (file_exists ?f)
    )
    :effect (and
      (not (file_exists ?f))
    )
  )

  ;; Action: delete_user
  (:action delete_user
    :parameters (?u - user)
    :precondition (and
      (user_exists ?u)
    )
    :effect (and
      (not (user_exists ?u))
    )
  )

  ;; Action: disable_service
  (:action disable_service
    :parameters (?s - service)
    :precondition (and
      (service_enabled ?s)
    )
    :effect (and
      (not (service_enabled ?s))
    )
  )

  ;; Action: enable_service
  (:action enable_service
    :parameters (?s - service)
    :precondition (and
      (service_exists ?s)
    )
    :effect (and
      (service_enabled ?s)
    )
  )

  ;; Action: install_package
  (:action install_package
    :parameters (?p - package)
    :precondition (and
      (not (package_installed ?p))
      (package_available ?p)
    )
    :effect (and)
  )

  ;; Action: move_file
  (:action move_file
    :parameters (?src - file ?dst - file)
    :precondition (and
      (file_exists ?src)
    )
    :effect (and
      (not (file_exists ?src))
      (file_exists ?dst)
    )
  )

  ;; Action: open_port
  (:action open_port
    :parameters (?p - port)
    :precondition (and
      (not (port_allowed ?p))
    )
    :effect (and
      (port_allowed ?p)
    )
  )

  ;; Action: remove_firewall_rule
  (:action remove_firewall_rule
    :parameters (?r - firewall_rule)
    :precondition (and
      (firewall_rule_active ?r)
    )
    :effect (and
      (not (firewall_rule_active ?r))
      (not (traffic_blocked ?r))
    )
  )

  ;; Action: remove_package
  (:action remove_package
    :parameters (?p - package)
    :precondition (and
      (installed ?p)
    )
    :effect (and
      (not (installed ?p))
    )
  )

  ;; Action: restart_service
  (:action restart_service
    :parameters (?s - service)
    :precondition (and
      (service_exists ?s)
    )
    :effect (and
      (service_running ?s)
    )
  )

  ;; Action: start_service
  (:action start_service
    :parameters (?s - service)
    :precondition (and)
    :effect (and)
  )

  ;; Action: stop_service
  (:action stop_service
    :parameters (?s - service)
    :precondition (and
      (service_running ?s)
    )
    :effect (and
      (not (service_running ?s))
    )
  )

  ;; Action: update_package
  (:action update_package
    :parameters (?p - package)
    :precondition (and
      (installed ?p)
      (network_available)
    )
    :effect (and
      (not (outdated ?p))
      (not (vulnerable ?p))
    )
  )

)