;; =============================================================================
;; SYSADMIN PDDL DOMAIN - Ubuntu 25.10 'Questing Quokka'
;; Auto-generated by Phase 2: Parallel Synthesis (Map-Reduce)
;; =============================================================================

(define (domain sysadmin)

  (:requirements :strips :typing :negative-preconditions)

  ;; Type Hierarchy
  (:types
    filesystem_object firewall_rule group interface package port process repository service user - object
    directory file - filesystem_object
    configuration_file - file
    human_user system_user - user
  )

  ;; Predicates
  (:predicates
    (network_available)
    (can_escalate ?u - user)
  )

  ;; Action: add_repository
  (:action add_repository
    :parameters (?r - repository)
    :precondition (and)
    :effect (and
      (?p :exists (available ?p))
    )
  )

  ;; Action: add_rule
  (:action add_rule
    :parameters ()
    :precondition (and
      (connected_to ?i ?p)
      (not (has_rule ?r ?p))
    )
    :effect (and
      (has_rule ?r ?p)
      (allowed ?p)
    )
  )

  ;; Action: block_rule
  (:action block_rule
    :parameters ()
    :precondition (and
      (connected_to ?i ?p)
      (has_rule ?r ?p)
    )
    :effect (and
      (not (allowed ?p))
      (blocked ?p)
    )
  )

  ;; Action: change_file_group
  (:action change_file_group
    :parameters (?file - file ?new_group - string)
    :precondition (and)
    :effect (and)
  )

  ;; Action: change_file_owner
  (:action change_file_owner
    :parameters (?file - file ?new_owner - string)
    :precondition (and)
    :effect (and)
  )

  ;; Action: change_file_permissions
  (:action change_file_permissions
    :parameters (?file - file ?permissions - string)
    :precondition (and)
    :effect (and)
  )

  ;; Action: check_dependencies
  (:action check_dependencies
    :parameters (?p - package)
    :precondition (and)
    :effect (and
      (?d - dependency :exists (and (depends_on ?p ?d) (available ?d)))
    )
  )

  ;; Action: configure_interface
  (:action configure_interface
    :parameters ()
    :precondition (and
      (connected_to ?i ?p)
    )
    :effect (and)
  )

  ;; Action: copy_file
  (:action copy_file
    :parameters (?source_file - file ?destination_file - file)
    :precondition (and
      (is_file ?source_file)
      (is_file ?destination_file)
      (not (at_location ?destination_file))
    )
    :effect (and
      (at_location ?source_file)
      (not (at_location ?destination_file))
      (at_location ?destination_file)
    )
  )

  ;; Action: create_configuration_file
  (:action create_configuration_file
    :parameters (?configuration_file - configuration_file ?content - string)
    :precondition (and
      (at_location ?configuration_file)
    )
    :effect (and)
  )

  ;; Action: create_directory
  (:action create_directory
    :parameters (?directory - directory)
    :precondition (and
      (at_location ?directory)
    )
    :effect (and)
  )

  ;; Action: create_process
  (:action create_process
    :parameters (?process - process ?command - string)
    :precondition (and
      (process_id ?process)
    )
    :effect (and
      (process_id ?process)
      (process_is_root ?process)
      (not (process_is_authenticated ?process))
    )
  )

  ;; Action: disconnect_interface
  (:action disconnect_interface
    :parameters ()
    :precondition (and)
    :effect (and
      (connected_to ?i ?p)
    )
  )

  ;; Action: execute_command
  (:action execute_command
    :parameters (?user - user ?command - string)
    :precondition (and
      (user_is_authenticated ?user)
      (user_has_privilege ?user :execute_command)
    )
    :effect (and
      (process_is_root (create_process ?command))
      (process_is_authenticated (create_process ?command))
    )
  )

  ;; Action: find_newest_version
  (:action find_newest_version
    :parameters (?p - package)
    :precondition (and)
    :effect (and
      (and (available (package ?newest_version)) (depends_on ?p ?newest_version) (not (exists ?v :exists (and (available (package ?v)) (depends_on ?p ?v) (> (version_number ?v) (version_number ?newest_version))))))
    )
  )

  ;; Action: install_dependencies
  (:action install_dependencies
    :parameters (?p - package)
    :precondition (and)
    :effect (and
      (?d - dependency :exists (and (depends_on ?p ?d) (not (installed ?d)) (install_package ?d system_repository)))
    )
  )

  ;; Action: install_package
  (:action install_package
    :parameters (?p - package ?r - repository)
    :precondition (and
      (in_repository ?p ?r)
      (not (installed ?p))
    )
    :effect (and
      (installed ?p)
      (in_repository ?p ?r)
    )
  )

  ;; Action: iptables_add_rule
  (:action iptables_add_rule
    :parameters ()
    :precondition (and
      (equal ?chain "filter")
      (equal ?rule "ACCEPT")
    )
    :effect (and
      (allowed ?p)
      (has_rule ?r ?p)
    )
  )

  ;; Action: iptables_block_rule
  (:action iptables_block_rule
    :parameters ()
    :precondition (and
      (equal ?chain "filter")
      (equal ?rule "DROP")
    )
    :effect (and
      (blocked ?p)
      (has_rule ?r ?p)
    )
  )

  ;; Action: list_units
  (:action list_units
    :parameters (?units - list_of_services)
    :precondition (and
      (active_service systemd)
    )
    :effect (and
      (forall (?s in ?units) (active_service ?s))
      )()((active_service systemd_journal)
      )((forall (?e in ?entries) (journal_entry ?e))
      )()((active_service systemd_journal)
      )((forall (?e in ?filtered_entries) (matched_journal_entry ?e))
      )()((active_service systemd)
      )((= kernel_time (time_spent_in_kernel))
      (= initrd_time (time_spent_in_initrd))
      (= userspace_time (time_spent_in_userspace))
    )
  )

  ;; Action: modify_configuration_file
  (:action modify_configuration_file
    :parameters (?configuration_file - configuration_file ?new_content - string)
    :precondition (and)
    :effect (and)
  )

  ;; Action: move_file
  (:action move_file
    :parameters (?source_file - file ?destination_directory - directory)
    :precondition (and
      (is_file ?source_file)
      (is_directory ?destination_directory)
      (not (at_location ?destination_directory))
    )
    :effect (and
      (not (at_location ?source_file))
      (at_location ?destination_directory)
      (at_location (concat ?destination_directory "/" (name ?source_file)))
      (not (at_location (concat ?destination_directory "/" (name ?source_file))))
    )
  )

  ;; Action: nft_add_rule
  (:action nft_add_rule
    :parameters ()
    :precondition (and
      (equal ?chain "filter")
      (equal ?rule "accept")
    )
    :effect (and
      (allowed ?p)
      (has_rule ?r ?p)
    )
  )

  ;; Action: nft_block_rule
  (:action nft_block_rule
    :parameters ()
    :precondition (and
      (equal ?chain "filter")
      (equal ?rule "reject")
    )
    :effect (and
      (blocked ?p)
      (has_rule ?r ?p)
    )
  )

  ;; Action: pkexec
  (:action pkexec
    :parameters (?user - user ?command - string)
    :precondition (and
      (user_is_authenticated ?user)
      (user_has_privilege ?user :pkexec)
    )
    :effect (and
      (process_is_root (create_process (strcat "pkexec " ?user " " ?command)))
      (process_is_authenticated (create_process (strcat "pkexec " ?user " " ?command)))
    )
  )

  ;; Action: remove_dependencies
  (:action remove_dependencies
    :parameters (?p - package)
    :precondition (and)
    :effect (and
      (?d - dependency :exists (and (depends_on ?p ?d) (installed ?d) (remove_package ?d)))
    )
  )

  ;; Action: remove_directory
  (:action remove_directory
    :parameters (?directory - directory)
    :precondition (and)
    :effect (and
      (at_location ?directory)
    )
  )

  ;; Action: remove_package
  (:action remove_package
    :parameters (?p - package)
    :precondition (and)
    :effect (and
      (installed ?p)
    )
  )

  ;; Action: remove_repository
  (:action remove_repository
    :parameters (?r - repository)
    :precondition (and
      (?p :exists (available ?p))
    )
    :effect (and
      (in_repository ?p ?r)
      (?p :exists (available ?p))
    )
  )

  ;; Action: search_package
  (:action search_package
    :parameters (?name - string)
    :precondition (and)
    :effect (and
      (and (available ?p) (name ?name))
    )
  )

  ;; Action: su
  (:action su
    :parameters (?user - user ?command - string)
    :precondition (and
      (user_is_authenticated ?user)
      (user_has_privilege ?user :su)
    )
    :effect (and
      (process_is_root (create_process (strcat "su - " ?user " " ?command)))
      (process_is_authenticated (create_process (strcat "su - " ?user " " ?command)))
    )
  )

  ;; Action: sudo
  (:action sudo
    :parameters (?user - user ?command - string)
    :precondition (and
      (user_is_authenticated ?user)
      (user_has_privilege ?user :sudo)
    )
    :effect (and
      (process_is_root (create_process (strcat "sudo " ?command)))
      (process_is_authenticated (create_process (strcat "sudo " ?command)))
    )
  )

  ;; Action: ufw_allow
  (:action ufw_allow
    :parameters ()
    :precondition (and)
    :effect (and
      (allowed ?p)
      (has_rule ?r ?p)
    )
  )

  ;; Action: ufw_block
  (:action ufw_block
    :parameters ()
    :precondition (and)
    :effect (and
      (blocked ?p)
      (has_rule ?r ?p)
    )
  )

  ;; Action: update_package_list
  (:action update_package_list
    :parameters ()
    :precondition (and)
    :effect (and
      (available ?p)
      (in_repository ?p system_repository)
      (?p :exists (in_repository ?p system_repository))
    )
  )

  ;; Action: upgrade_package
  (:action upgrade_package
    :parameters (?p - package)
    :precondition (and
      (installed ?p)
      (available ?p)
    )
    :effect (and
      (not (installed ?p))
      (installed (find_newest_version ?p))
    )
  )

)