;; =============================================================================
;; SYSADMIN PDDL DOMAIN - Ubuntu 25.10 'Questing Quokka'
;; Auto-generated by Phase 2: Parallel Synthesis (Map-Reduce)
;; =============================================================================

(define (domain sysadmin)

  (:requirements :strips :typing :negative-preconditions)

  ;; Type Hierarchy
  (:types
    filesystem_object firewall_rule group interface package port process repository service user - object
    directory file - filesystem_object
    configuration_file - file
    human_user system_user - user
  )

  ;; Predicates
  (:predicates
    (network_available)
    (can_escalate ?u - user)
  )

)