(define (problem sysadmin-initial)
  (:domain sysadmin)

  (:objects
    user_root user_sync user__apt user_nobody user_dhcpcd user_syslog user_dnsmasq user_usbmux user_cups-pk-helper user_cups-browsed user_gnome-initial-setup user_resbears - user
    group_root group_adm group_cdrom group_sudo group_dip group_plugdev group_users group_nogroup group_syslog group_lpadmin group_resbears - group
    process_systemd process_vgauthservice process_vmtoolsd process_chronyd-starter process_networkd-dispat process_accounts-daemon process_cron process_switcheroo-cont process_systemd-logind process_udisksd process_rsyslogd process_networkmanager process_wpa_supplicant process_modemmanager process_cupsd process_unattended-upgr process_gdm3 process_cups-browsed process_kthreadd process_code process_upowerd process_irq_16-vmwgfx process_bash process_ruff process_python process_osqueryi process_power-profiles- process_gdm-session-wor process_systemd_1 process__sd-pam_ process_dbus-daemon process_pipewire process_pipewire_1 process_gnome-keyring-d process_mpris-proxy process_wireplumber process_pipewire-pulse process_gdm-wayland-ses process_gnome-session-i process_xdg-document-po process_xdg-permission- process_fusermount3 process_gcr-ssh-agent process_gnome-session-c process_ssh-agent process_gvfsd process_gvfsd-fuse process_gnome-session-s process_gnome-shell process_at-spi-bus-laun process_dbus-daemon_1 process_at-spi2-registr process_gnome-shell-cal process_evolution-sourc process_gjs process_ibus-daemon process_gsd-a11y-settin process_gsd-color process_gsd-datetime process_gsd-housekeepin process_gsd-keyboard process_gsd-media-keys process_gsd-power process_gsd-print-notif process_gsd-rfkill process_gsd-screensaver process_sh process_xwayland process_gsd-sharing process_snap process_ubuntu-advantag process_update-notifier process_evolution-alarm process_gsd-smartcard process_vmware-user-sui process_ubuntu-report process_gsd-disk-utilit process_vmtoolsd_1 process_gsd-sound process_gjs_1 process_goa-daemon process_bwrap process_gsd-usb-protect process_gsd-wwan process_bwrap_1 process_glycin-image-rs process_ibus-dconf process_ibus-extension- process_gsd-printer process_gvfs-udisks2-vo process_pool_workqueue_release process_ibus-portal process_evolution-calen process_goa-identity-se process_localsearch-3 process_gvfs-gphoto2-vo process_evolution-addre process_gvfs-goa-volume process_gvfsd-metadata process_gvfs-afc-volume process_gvfs-mtp-volume process_ibus-engine-sim process_dconf-service process_gvfsd-trash process_scsi_eh_2 process_gjs_2 process_scsi_eh_3 process_scsi_eh_4 process_scsi_eh_5 process_gsd-xsettings process_mutter-x11-fram process_xdg-desktop-por process_scsi_eh_6 process_xdg-desktop-por_1 process_scsi_eh_7 process_ibus-x11 process_scsi_eh_8 process_scsi_eh_9 process_xdg-desktop-por_2 process_scsi_eh_10 process_scsi_eh_11 process_scsi_eh_12 process_scsi_eh_13 process_scsi_eh_14 process_scsi_eh_15 process_obexd process_scsi_eh_16 process_scsi_eh_17 process_scsi_eh_18 process_scsi_eh_19 process_scsi_eh_20 process_scsi_eh_21 process_scsi_eh_22 process_scsi_eh_23 process_scsi_eh_24 process_scsi_eh_25 process_scsi_eh_26 process_scsi_eh_27 process_scsi_eh_28 process_scsi_eh_29 process_scsi_eh_30 process_scsi_eh_31 process_scsi_eh_32 process_code_1 process_code_2 process_code_3 process_chrome_crashpad process_kdevtmpfs process_code_4 process_code_5 process_code_6 process_code_7 process_code_8 process_code_9 process_code_10 process_pet process_bash_1 process_kauditd process_jbd2_sda2-8 process_khungtaskd process_code_11 process_code_12 process_oom_reaper process_systemd-journal process_kcompactd0 process_ksmd process_code_13 process_khugepaged process_systemd-udevd process_psimon process_irq_9-acpi process_snapd process_irq_26-vmw_vmci process_irq_27-vmw_vmci process_irq_28-vmw_vmci process_kswapd0 process_ecryptfs-kthread process_snapd-desktop-i process_snapd-desktop-i_1 process_scsi_eh_0 process_scsi_eh_1 process_psimon_1 process_fwupd process_vmware-vmblock- - process
    port_6_48369 port_6_53 port_6_5878 port_6_24855 port_6_37021 port_6_631 port_17_53 port_17_323 port_17_5353 port_255_58 port_0_0 port_2054_0 - port
    service_unattended-upgrades_service service_udisks2_service service_systemd-user-sessions_service service_systemd-fsck_dev-disk-by_x2duuid-9d28_x2d827c_service service_systemd-networkd-persistent-storage_service service_wpa_supplicant_service service_systemd-tmpfiles-setup-dev-early_service service_snapd_recovery-chooser-trigger_service service_dracut-pre-trigger_service service_systemd-fsck-root_service service_sysstat_service service_fwupd-refresh_service service_systemd-udevd_service service_systemd-rfkill_service service_systemd-oomd_service service_dracut-mount_service service_power-profiles-daemon_service service_systemd-bsod_service service_plymouth-kexec_service service_systemd-binfmt_service service_systemd-firstboot_service service_dracut-pre-udev_service service_systemd-udev-trigger_service service_systemd-modules-load_service service_systemd-quotacheck-root_service service_dracut-cmdline_service service_systemd-update-done_service service_systemd-sysext_service service_systemd-pcrphase-initrd_service service_systemd-confext_service service_systemd-ask-password-plymouth_service service_dracut-pre-pivot_service service_systemd-journald_service service_sysstat-collect_service service_systemd-poweroff_service service_systemd-tmpfiles-setup-dev_service service_systemd-quotacheck_service service_cups_service service_systemd-networkd-wait-online_service service_kdump-tools_service service_switcheroo-control_service service_systemd-kexec_service service_systemd-hibernate_service service_dracut-shutdown-onfailure_service service_dracut-initqueue_service service_systemd-journal-flush_service service_systemd-pcrphase-sysinit_service service_systemd-vconsole-setup_service service_kmod-static-nodes_service service_systemd-suspend-then-hibernate_service service_systemd-hybrid-sleep_service service_systemd-pstore_service service_snapd_apparmor_service service_systemd-logind_service service_systemd-ask-password-wall_service service_openvpn_service service_snapd_snap-repair_service service_dbus_service service_systemd-machine-id-commit_service service_apport-autoreport_service service_networkmanager_service service_dracut-shutdown_service service_systemd-reboot_service service_plymouth-quit-wait_service service_systemd-hibernate-clear_service service_apport_service service_fwupd_service service_systemd-ask-password-console_service service_accounts-daemon_service service_systemd-halt_service service_snapd_seeded_service service_systemd-pcrmachine_service service_upower_service service_plymouth-switch-root-initramfs_service service_user_1000_service service_colord_service service_plymouth-halt_service service_vgauth_service service_systemd-udev-load-credentials_service service_snapd_service service_sysstat-summary_service service_systemd-journal-catalog-update_service service_polkit_service service_systemd-tmpfiles-clean_service service_plymouth-read-write_service service_systemd-tmpfiles-setup_service service_networkmanager-wait-online_service service_systemd-battery-check_service service_systemd-hibernate-resume_service service_chrony_service service_systemd-hostnamed_service service_sysstat-rotate_service service_plymouth-reboot_service service_systemd-sysctl_service service_systemd-pcrphase_service service_dracut-pre-mount_service service_rtkit-daemon_service service_plymouth-switch-root_service service_user-runtime-dir_1000_service service_systemd-initctl_service service_systemd-resolved_service service_plymouth-start_service service_systemd-suspend_service service_apparmor_service service_systemd-tpm2-setup-early_service service_networkd-dispatcher_service service_cups-browsed_service service_keyboard-setup_service service_open-vm-tools_service service_systemd-udev-settle_service service_systemd-sysusers_service service_systemd-networkd_service service_snapd_core-fixup_service service_systemd-remount-fs_service service_ufw_service service_systemd-hwdb-update_service service_snapd_autoimport_service service_snapd_failure_service service_gdm_service service_plymouth-quit_service service_systemd-random-seed_service service_cron_service service_snapd_system-shutdown_service service_setvtrgb_service service_console-setup_service service_rsyslog_service service_systemd-tpm2-setup_service service_logrotate_service service_modemmanager_service service_systemd-soft-reboot_service service_avahi-daemon_service service_plymouth-poweroff_service - service
    package_apparmor package_apport package_avahi-daemon package_chrony package_colord package_console-setup package_cron package_cups package_cups-browsed package_dbus package_dracut package_fwupd package_gdm3 package_kdump-tools package_kmod package_logrotate package_networkd-dispatcher package_open-vm-tools package_openvpn package_plymouth package_polkitd package_power-profiles-daemon package_rsyslog package_rtkit package_snapd package_switcheroo-control package_sysstat package_systemd package_systemd-oomd package_systemd-resolved package_udisks2 package_ufw package_unattended-upgrades package_upower - package
    configuration_file__etc_adduser_conf configuration_file__etc_brltty_conf configuration_file__etc_ca-certificates_conf configuration_file__etc_debconf_conf configuration_file__etc_deluser_conf configuration_file__etc_dhcpcd_conf configuration_file__etc_dracut_conf configuration_file__etc_e2scrub_conf configuration_file__etc_fprintd_conf configuration_file__etc_fuse_conf configuration_file__etc_gai_conf configuration_file__etc_hdparm_conf configuration_file__etc_host_conf configuration_file__etc_ld_so_conf configuration_file__etc_libao_conf configuration_file__etc_libaudit_conf configuration_file__etc_locale_conf configuration_file__etc_logrotate_conf configuration_file__etc_mke2fs_conf configuration_file__etc_nftables_conf configuration_file__etc_nsswitch_conf configuration_file__etc_pam_conf configuration_file__etc_pnm2ppa_conf configuration_file__etc_rsyslog_conf configuration_file__etc_rygel_conf configuration_file__etc_sensors3_conf configuration_file__etc_sudo_conf configuration_file__etc_sudo_logsrvd_conf configuration_file__etc_ucf_conf configuration_file__etc_usb_modeswitch_conf configuration_file__etc_vconsole_conf configuration_file__etc_vdpau_wrapper_cfg configuration_file__etc_xattr_conf - configuration_file
  )

  (:init
    (user_exists user_root)
    (can_escalate user_root)
    (user_critical user_root)
    (user_exists user_sync)
    (user_critical user_sync)
    (user_exists user__apt)
    (user_critical user__apt)
    (user_exists user_nobody)
    (user_exists user_dhcpcd)
    (user_critical user_dhcpcd)
    (user_exists user_syslog)
    (user_critical user_syslog)
    (user_exists user_dnsmasq)
    (user_critical user_dnsmasq)
    (user_exists user_usbmux)
    (user_critical user_usbmux)
    (user_exists user_cups-pk-helper)
    (user_critical user_cups-pk-helper)
    (user_exists user_cups-browsed)
    (user_critical user_cups-browsed)
    (user_exists user_gnome-initial-setup)
    (user_critical user_gnome-initial-setup)
    (user_exists user_resbears)
    (can_escalate user_resbears)
    (process_running process_systemd)
    (process_running process_vgauthservice)
    (process_running process_vmtoolsd)
    (process_running process_chronyd-starter)
    (process_running process_networkd-dispat)
    (process_running process_accounts-daemon)
    (process_running process_cron)
    (process_running process_switcheroo-cont)
    (process_running process_systemd-logind)
    (process_running process_udisksd)
    (process_running process_rsyslogd)
    (process_running process_networkmanager)
    (process_running process_wpa_supplicant)
    (process_running process_modemmanager)
    (process_running process_cupsd)
    (process_running process_unattended-upgr)
    (process_running process_gdm3)
    (process_running process_cups-browsed)
    (process_running process_kthreadd)
    (process_running process_code)
    (process_running process_upowerd)
    (process_running process_irq_16-vmwgfx)
    (process_running process_bash)
    (process_running process_ruff)
    (process_running process_python)
    (process_running process_osqueryi)
    (process_running process_power-profiles-)
    (process_running process_gdm-session-wor)
    (process_running process_systemd_1)
    (process_running process__sd-pam_)
    (process_running process_dbus-daemon)
    (process_running process_pipewire)
    (process_running process_pipewire_1)
    (process_running process_gnome-keyring-d)
    (process_running process_mpris-proxy)
    (process_running process_wireplumber)
    (process_running process_pipewire-pulse)
    (process_running process_gdm-wayland-ses)
    (process_running process_gnome-session-i)
    (process_running process_xdg-document-po)
    (process_running process_xdg-permission-)
    (process_running process_fusermount3)
    (process_running process_gcr-ssh-agent)
    (process_running process_gnome-session-c)
    (process_running process_ssh-agent)
    (process_running process_gvfsd)
    (process_running process_gvfsd-fuse)
    (process_running process_gnome-session-s)
    (process_running process_gnome-shell)
    (process_running process_at-spi-bus-laun)
    (process_running process_dbus-daemon_1)
    (process_running process_at-spi2-registr)
    (process_running process_gnome-shell-cal)
    (process_running process_evolution-sourc)
    (process_running process_gjs)
    (process_running process_ibus-daemon)
    (process_running process_gsd-a11y-settin)
    (process_running process_gsd-color)
    (process_running process_gsd-datetime)
    (process_running process_gsd-housekeepin)
    (process_running process_gsd-keyboard)
    (process_running process_gsd-media-keys)
    (process_running process_gsd-power)
    (process_running process_gsd-print-notif)
    (process_running process_gsd-rfkill)
    (process_running process_gsd-screensaver)
    (process_running process_xwayland)
    (process_running process_gsd-sharing)
    (process_running process_update-notifier)
    (process_running process_evolution-alarm)
    (process_running process_gsd-smartcard)
    (process_running process_gsd-disk-utilit)
    (process_running process_vmtoolsd_1)
    (process_running process_gsd-sound)
    (process_running process_gjs_1)
    (process_running process_goa-daemon)
    (process_running process_bwrap)
    (process_running process_gsd-usb-protect)
    (process_running process_gsd-wwan)
    (process_running process_bwrap_1)
    (process_running process_glycin-image-rs)
    (process_running process_ibus-dconf)
    (process_running process_ibus-extension-)
    (process_running process_gsd-printer)
    (process_running process_gvfs-udisks2-vo)
    (process_running process_pool_workqueue_release)
    (process_running process_ibus-portal)
    (process_running process_evolution-calen)
    (process_running process_goa-identity-se)
    (process_running process_localsearch-3)
    (process_running process_gvfs-gphoto2-vo)
    (process_running process_evolution-addre)
    (process_running process_gvfs-goa-volume)
    (process_running process_gvfsd-metadata)
    (process_running process_gvfs-afc-volume)
    (process_running process_gvfs-mtp-volume)
    (process_running process_ibus-engine-sim)
    (process_running process_dconf-service)
    (process_running process_gvfsd-trash)
    (process_running process_scsi_eh_2)
    (process_running process_gjs_2)
    (process_running process_scsi_eh_3)
    (process_running process_scsi_eh_4)
    (process_running process_scsi_eh_5)
    (process_running process_gsd-xsettings)
    (process_running process_mutter-x11-fram)
    (process_running process_xdg-desktop-por)
    (process_running process_scsi_eh_6)
    (process_running process_xdg-desktop-por_1)
    (process_running process_scsi_eh_7)
    (process_running process_ibus-x11)
    (process_running process_scsi_eh_8)
    (process_running process_scsi_eh_9)
    (process_running process_xdg-desktop-por_2)
    (process_running process_scsi_eh_10)
    (process_running process_scsi_eh_11)
    (process_running process_scsi_eh_12)
    (process_running process_scsi_eh_13)
    (process_running process_scsi_eh_14)
    (process_running process_scsi_eh_15)
    (process_running process_obexd)
    (process_running process_scsi_eh_16)
    (process_running process_scsi_eh_17)
    (process_running process_scsi_eh_18)
    (process_running process_scsi_eh_19)
    (process_running process_scsi_eh_20)
    (process_running process_scsi_eh_21)
    (process_running process_scsi_eh_22)
    (process_running process_scsi_eh_23)
    (process_running process_scsi_eh_24)
    (process_running process_scsi_eh_25)
    (process_running process_scsi_eh_26)
    (process_running process_scsi_eh_27)
    (process_running process_scsi_eh_28)
    (process_running process_scsi_eh_29)
    (process_running process_scsi_eh_30)
    (process_running process_scsi_eh_31)
    (process_running process_scsi_eh_32)
    (process_running process_code_1)
    (process_running process_code_2)
    (process_running process_code_3)
    (process_running process_chrome_crashpad)
    (process_running process_kdevtmpfs)
    (process_running process_code_4)
    (process_running process_code_5)
    (process_running process_code_6)
    (process_running process_code_7)
    (process_running process_code_8)
    (process_running process_code_9)
    (process_running process_code_10)
    (process_running process_pet)
    (process_running process_bash_1)
    (process_running process_kauditd)
    (process_running process_jbd2_sda2-8)
    (process_running process_khungtaskd)
    (process_running process_code_11)
    (process_running process_code_12)
    (process_running process_oom_reaper)
    (process_running process_systemd-journal)
    (process_running process_kcompactd0)
    (process_running process_ksmd)
    (process_running process_code_13)
    (process_running process_khugepaged)
    (process_running process_systemd-udevd)
    (process_running process_psimon)
    (process_running process_irq_9-acpi)
    (process_running process_snapd)
    (process_running process_irq_26-vmw_vmci)
    (process_running process_irq_27-vmw_vmci)
    (process_running process_irq_28-vmw_vmci)
    (process_running process_kswapd0)
    (process_running process_ecryptfs-kthread)
    (process_running process_snapd-desktop-i)
    (process_running process_snapd-desktop-i_1)
    (process_running process_scsi_eh_0)
    (process_running process_scsi_eh_1)
    (process_running process_psimon_1)
    (process_running process_fwupd)
    (process_running process_vmware-vmblock-)
    (port_open port_6_48369)
    (port_open port_6_53)
    (port_open port_6_5878)
    (port_open port_6_24855)
    (port_open port_6_37021)
    (port_open port_6_631)
    (port_open port_17_53)
    (port_open port_17_323)
    (port_open port_17_5353)
    (port_open port_255_58)
    (port_open port_0_0)
    (port_open port_2054_0)
    (service_exists service_unattended-upgrades_service)
    (service_running service_unattended-upgrades_service)
    (service_enabled service_unattended-upgrades_service)
    (service_exists service_udisks2_service)
    (service_running service_udisks2_service)
    (service_enabled service_udisks2_service)
    (service_exists service_systemd-user-sessions_service)
    (service_running service_systemd-user-sessions_service)
    (service_enabled service_systemd-user-sessions_service)
    (service_exists service_systemd-fsck_dev-disk-by_x2duuid-9d28_x2d827c_service)
    (service_running service_systemd-fsck_dev-disk-by_x2duuid-9d28_x2d827c_service)
    (service_enabled service_systemd-fsck_dev-disk-by_x2duuid-9d28_x2d827c_service)
    (service_exists service_systemd-networkd-persistent-storage_service)
    (service_enabled service_systemd-networkd-persistent-storage_service)
    (service_exists service_wpa_supplicant_service)
    (service_running service_wpa_supplicant_service)
    (service_enabled service_wpa_supplicant_service)
    (service_exists service_systemd-tmpfiles-setup-dev-early_service)
    (service_running service_systemd-tmpfiles-setup-dev-early_service)
    (service_enabled service_systemd-tmpfiles-setup-dev-early_service)
    (service_exists service_snapd_recovery-chooser-trigger_service)
    (service_enabled service_snapd_recovery-chooser-trigger_service)
    (service_exists service_dracut-pre-trigger_service)
    (service_enabled service_dracut-pre-trigger_service)
    (service_exists service_systemd-fsck-root_service)
    (service_running service_systemd-fsck-root_service)
    (service_enabled service_systemd-fsck-root_service)
    (service_exists service_sysstat_service)
    (service_running service_sysstat_service)
    (service_enabled service_sysstat_service)
    (service_exists service_fwupd-refresh_service)
    (service_enabled service_fwupd-refresh_service)
    (service_exists service_systemd-udevd_service)
    (service_running service_systemd-udevd_service)
    (service_enabled service_systemd-udevd_service)
    (service_exists service_systemd-rfkill_service)
    (service_enabled service_systemd-rfkill_service)
    (service_exists service_systemd-oomd_service)
    (service_running service_systemd-oomd_service)
    (service_enabled service_systemd-oomd_service)
    (service_exists service_dracut-mount_service)
    (service_enabled service_dracut-mount_service)
    (service_exists service_power-profiles-daemon_service)
    (service_running service_power-profiles-daemon_service)
    (service_enabled service_power-profiles-daemon_service)
    (service_exists service_systemd-bsod_service)
    (service_enabled service_systemd-bsod_service)
    (service_exists service_plymouth-kexec_service)
    (service_enabled service_plymouth-kexec_service)
    (service_exists service_systemd-binfmt_service)
    (service_running service_systemd-binfmt_service)
    (service_enabled service_systemd-binfmt_service)
    (service_exists service_systemd-firstboot_service)
    (service_enabled service_systemd-firstboot_service)
    (service_exists service_dracut-pre-udev_service)
    (service_enabled service_dracut-pre-udev_service)
    (service_exists service_systemd-udev-trigger_service)
    (service_running service_systemd-udev-trigger_service)
    (service_enabled service_systemd-udev-trigger_service)
    (service_exists service_systemd-modules-load_service)
    (service_running service_systemd-modules-load_service)
    (service_enabled service_systemd-modules-load_service)
    (service_exists service_systemd-quotacheck-root_service)
    (service_enabled service_systemd-quotacheck-root_service)
    (service_exists service_dracut-cmdline_service)
    (service_enabled service_dracut-cmdline_service)
    (service_exists service_systemd-update-done_service)
    (service_enabled service_systemd-update-done_service)
    (service_exists service_systemd-sysext_service)
    (service_enabled service_systemd-sysext_service)
    (service_exists service_systemd-pcrphase-initrd_service)
    (service_enabled service_systemd-pcrphase-initrd_service)
    (service_exists service_systemd-confext_service)
    (service_enabled service_systemd-confext_service)
    (service_exists service_systemd-ask-password-plymouth_service)
    (service_enabled service_systemd-ask-password-plymouth_service)
    (service_exists service_dracut-pre-pivot_service)
    (service_enabled service_dracut-pre-pivot_service)
    (service_exists service_systemd-journald_service)
    (service_running service_systemd-journald_service)
    (service_enabled service_systemd-journald_service)
    (service_exists service_sysstat-collect_service)
    (service_enabled service_sysstat-collect_service)
    (service_exists service_systemd-poweroff_service)
    (service_enabled service_systemd-poweroff_service)
    (service_exists service_systemd-tmpfiles-setup-dev_service)
    (service_running service_systemd-tmpfiles-setup-dev_service)
    (service_enabled service_systemd-tmpfiles-setup-dev_service)
    (service_exists service_systemd-quotacheck_service)
    (service_exists service_cups_service)
    (service_running service_cups_service)
    (service_enabled service_cups_service)
    (service_exists service_systemd-networkd-wait-online_service)
    (service_enabled service_systemd-networkd-wait-online_service)
    (service_exists service_kdump-tools_service)
    (service_running service_kdump-tools_service)
    (service_enabled service_kdump-tools_service)
    (service_exists service_switcheroo-control_service)
    (service_running service_switcheroo-control_service)
    (service_enabled service_switcheroo-control_service)
    (service_exists service_systemd-kexec_service)
    (service_enabled service_systemd-kexec_service)
    (service_exists service_systemd-hibernate_service)
    (service_enabled service_systemd-hibernate_service)
    (service_exists service_dracut-shutdown-onfailure_service)
    (service_enabled service_dracut-shutdown-onfailure_service)
    (service_exists service_dracut-initqueue_service)
    (service_enabled service_dracut-initqueue_service)
    (service_exists service_systemd-journal-flush_service)
    (service_running service_systemd-journal-flush_service)
    (service_enabled service_systemd-journal-flush_service)
    (service_exists service_systemd-pcrphase-sysinit_service)
    (service_enabled service_systemd-pcrphase-sysinit_service)
    (service_exists service_systemd-vconsole-setup_service)
    (service_exists service_kmod-static-nodes_service)
    (service_running service_kmod-static-nodes_service)
    (service_enabled service_kmod-static-nodes_service)
    (service_exists service_systemd-suspend-then-hibernate_service)
    (service_enabled service_systemd-suspend-then-hibernate_service)
    (service_exists service_systemd-hybrid-sleep_service)
    (service_enabled service_systemd-hybrid-sleep_service)
    (service_exists service_systemd-pstore_service)
    (service_enabled service_systemd-pstore_service)
    (service_exists service_snapd_apparmor_service)
    (service_running service_snapd_apparmor_service)
    (service_enabled service_snapd_apparmor_service)
    (service_exists service_systemd-logind_service)
    (service_running service_systemd-logind_service)
    (service_enabled service_systemd-logind_service)
    (service_exists service_systemd-ask-password-wall_service)
    (service_enabled service_systemd-ask-password-wall_service)
    (service_exists service_openvpn_service)
    (service_running service_openvpn_service)
    (service_enabled service_openvpn_service)
    (service_exists service_snapd_snap-repair_service)
    (service_enabled service_snapd_snap-repair_service)
    (service_exists service_dbus_service)
    (service_running service_dbus_service)
    (service_enabled service_dbus_service)
    (service_exists service_systemd-machine-id-commit_service)
    (service_enabled service_systemd-machine-id-commit_service)
    (service_exists service_apport-autoreport_service)
    (service_enabled service_apport-autoreport_service)
    (service_exists service_networkmanager_service)
    (service_running service_networkmanager_service)
    (service_enabled service_networkmanager_service)
    (service_exists service_dracut-shutdown_service)
    (service_running service_dracut-shutdown_service)
    (service_enabled service_dracut-shutdown_service)
    (service_exists service_systemd-reboot_service)
    (service_enabled service_systemd-reboot_service)
    (service_exists service_plymouth-quit-wait_service)
    (service_running service_plymouth-quit-wait_service)
    (service_enabled service_plymouth-quit-wait_service)
    (service_exists service_systemd-hibernate-clear_service)
    (service_enabled service_systemd-hibernate-clear_service)
    (service_exists service_apport_service)
    (service_running service_apport_service)
    (service_enabled service_apport_service)
    (service_exists service_fwupd_service)
    (service_running service_fwupd_service)
    (service_enabled service_fwupd_service)
    (service_exists service_systemd-ask-password-console_service)
    (service_enabled service_systemd-ask-password-console_service)
    (service_exists service_accounts-daemon_service)
    (service_running service_accounts-daemon_service)
    (service_enabled service_accounts-daemon_service)
    (service_exists service_systemd-halt_service)
    (service_enabled service_systemd-halt_service)
    (service_exists service_snapd_seeded_service)
    (service_running service_snapd_seeded_service)
    (service_enabled service_snapd_seeded_service)
    (service_exists service_systemd-pcrmachine_service)
    (service_enabled service_systemd-pcrmachine_service)
    (service_exists service_upower_service)
    (service_running service_upower_service)
    (service_enabled service_upower_service)
    (service_exists service_plymouth-switch-root-initramfs_service)
    (service_enabled service_plymouth-switch-root-initramfs_service)
    (service_exists service_user_1000_service)
    (service_running service_user_1000_service)
    (service_enabled service_user_1000_service)
    (service_exists service_colord_service)
    (service_running service_colord_service)
    (service_enabled service_colord_service)
    (service_exists service_plymouth-halt_service)
    (service_enabled service_plymouth-halt_service)
    (service_exists service_vgauth_service)
    (service_running service_vgauth_service)
    (service_enabled service_vgauth_service)
    (service_exists service_systemd-udev-load-credentials_service)
    (service_running service_systemd-udev-load-credentials_service)
    (service_enabled service_systemd-udev-load-credentials_service)
    (service_exists service_snapd_service)
    (service_running service_snapd_service)
    (service_enabled service_snapd_service)
    (service_exists service_sysstat-summary_service)
    (service_enabled service_sysstat-summary_service)
    (service_exists service_systemd-journal-catalog-update_service)
    (service_enabled service_systemd-journal-catalog-update_service)
    (service_exists service_polkit_service)
    (service_running service_polkit_service)
    (service_enabled service_polkit_service)
    (service_exists service_systemd-tmpfiles-clean_service)
    (service_enabled service_systemd-tmpfiles-clean_service)
    (service_exists service_plymouth-read-write_service)
    (service_running service_plymouth-read-write_service)
    (service_enabled service_plymouth-read-write_service)
    (service_exists service_systemd-tmpfiles-setup_service)
    (service_running service_systemd-tmpfiles-setup_service)
    (service_enabled service_systemd-tmpfiles-setup_service)
    (service_exists service_networkmanager-wait-online_service)
    (service_running service_networkmanager-wait-online_service)
    (service_enabled service_networkmanager-wait-online_service)
    (service_exists service_systemd-battery-check_service)
    (service_enabled service_systemd-battery-check_service)
    (service_exists service_systemd-hibernate-resume_service)
    (service_enabled service_systemd-hibernate-resume_service)
    (service_exists service_chrony_service)
    (service_running service_chrony_service)
    (service_enabled service_chrony_service)
    (service_exists service_systemd-hostnamed_service)
    (service_enabled service_systemd-hostnamed_service)
    (service_exists service_sysstat-rotate_service)
    (service_enabled service_sysstat-rotate_service)
    (service_exists service_plymouth-reboot_service)
    (service_enabled service_plymouth-reboot_service)
    (service_exists service_systemd-sysctl_service)
    (service_running service_systemd-sysctl_service)
    (service_enabled service_systemd-sysctl_service)
    (service_exists service_systemd-pcrphase_service)
    (service_enabled service_systemd-pcrphase_service)
    (service_exists service_dracut-pre-mount_service)
    (service_enabled service_dracut-pre-mount_service)
    (service_exists service_rtkit-daemon_service)
    (service_running service_rtkit-daemon_service)
    (service_enabled service_rtkit-daemon_service)
    (service_exists service_plymouth-switch-root_service)
    (service_enabled service_plymouth-switch-root_service)
    (service_exists service_user-runtime-dir_1000_service)
    (service_running service_user-runtime-dir_1000_service)
    (service_enabled service_user-runtime-dir_1000_service)
    (service_exists service_systemd-initctl_service)
    (service_enabled service_systemd-initctl_service)
    (service_exists service_systemd-resolved_service)
    (service_running service_systemd-resolved_service)
    (service_enabled service_systemd-resolved_service)
    (service_exists service_plymouth-start_service)
    (service_running service_plymouth-start_service)
    (service_enabled service_plymouth-start_service)
    (service_exists service_systemd-suspend_service)
    (service_enabled service_systemd-suspend_service)
    (service_exists service_apparmor_service)
    (service_running service_apparmor_service)
    (service_enabled service_apparmor_service)
    (service_exists service_systemd-tpm2-setup-early_service)
    (service_enabled service_systemd-tpm2-setup-early_service)
    (service_exists service_networkd-dispatcher_service)
    (service_running service_networkd-dispatcher_service)
    (service_enabled service_networkd-dispatcher_service)
    (service_exists service_cups-browsed_service)
    (service_running service_cups-browsed_service)
    (service_enabled service_cups-browsed_service)
    (service_exists service_keyboard-setup_service)
    (service_running service_keyboard-setup_service)
    (service_enabled service_keyboard-setup_service)
    (service_exists service_open-vm-tools_service)
    (service_running service_open-vm-tools_service)
    (service_enabled service_open-vm-tools_service)
    (service_exists service_systemd-udev-settle_service)
    (service_enabled service_systemd-udev-settle_service)
    (service_exists service_systemd-sysusers_service)
    (service_enabled service_systemd-sysusers_service)
    (service_exists service_systemd-networkd_service)
    (service_enabled service_systemd-networkd_service)
    (service_exists service_snapd_core-fixup_service)
    (service_enabled service_snapd_core-fixup_service)
    (service_exists service_systemd-remount-fs_service)
    (service_running service_systemd-remount-fs_service)
    (service_enabled service_systemd-remount-fs_service)
    (service_exists service_ufw_service)
    (service_running service_ufw_service)
    (service_enabled service_ufw_service)
    (service_exists service_systemd-hwdb-update_service)
    (service_enabled service_systemd-hwdb-update_service)
    (service_exists service_snapd_autoimport_service)
    (service_enabled service_snapd_autoimport_service)
    (service_exists service_snapd_failure_service)
    (service_enabled service_snapd_failure_service)
    (service_exists service_gdm_service)
    (service_running service_gdm_service)
    (service_enabled service_gdm_service)
    (service_exists service_plymouth-quit_service)
    (service_enabled service_plymouth-quit_service)
    (service_exists service_systemd-random-seed_service)
    (service_running service_systemd-random-seed_service)
    (service_enabled service_systemd-random-seed_service)
    (service_exists service_cron_service)
    (service_running service_cron_service)
    (service_enabled service_cron_service)
    (service_exists service_snapd_system-shutdown_service)
    (service_enabled service_snapd_system-shutdown_service)
    (service_exists service_setvtrgb_service)
    (service_running service_setvtrgb_service)
    (service_enabled service_setvtrgb_service)
    (service_exists service_console-setup_service)
    (service_running service_console-setup_service)
    (service_enabled service_console-setup_service)
    (service_exists service_rsyslog_service)
    (service_running service_rsyslog_service)
    (service_enabled service_rsyslog_service)
    (service_exists service_systemd-tpm2-setup_service)
    (service_enabled service_systemd-tpm2-setup_service)
    (service_exists service_logrotate_service)
    (service_enabled service_logrotate_service)
    (service_exists service_modemmanager_service)
    (service_running service_modemmanager_service)
    (service_enabled service_modemmanager_service)
    (service_exists service_systemd-soft-reboot_service)
    (service_enabled service_systemd-soft-reboot_service)
    (service_exists service_avahi-daemon_service)
    (service_running service_avahi-daemon_service)
    (service_enabled service_avahi-daemon_service)
    (service_exists service_plymouth-poweroff_service)
    (service_enabled service_plymouth-poweroff_service)
    (package_installed package_apparmor)
    (package_installed package_apport)
    (package_installed package_avahi-daemon)
    (package_installed package_chrony)
    (package_installed package_colord)
    (package_installed package_console-setup)
    (package_installed package_cron)
    (package_installed package_cups)
    (package_installed package_cups-browsed)
    (package_installed package_dbus)
    (package_installed package_dracut)
    (package_installed package_fwupd)
    (package_installed package_gdm3)
    (package_installed package_kdump-tools)
    (package_installed package_kmod)
    (package_installed package_logrotate)
    (package_installed package_networkd-dispatcher)
    (package_installed package_open-vm-tools)
    (package_installed package_openvpn)
    (package_installed package_plymouth)
    (package_installed package_polkitd)
    (package_installed package_power-profiles-daemon)
    (package_installed package_rsyslog)
    (package_installed package_rtkit)
    (package_installed package_snapd)
    (package_installed package_switcheroo-control)
    (package_installed package_sysstat)
    (package_installed package_systemd)
    (package_installed package_systemd-oomd)
    (package_installed package_systemd-resolved)
    (package_installed package_udisks2)
    (package_installed package_ufw)
    (package_installed package_unattended-upgrades)
    (package_installed package_upower)
    (file_exists configuration_file__etc_adduser_conf)
    (file_exists configuration_file__etc_brltty_conf)
    (file_exists configuration_file__etc_ca-certificates_conf)
    (file_exists configuration_file__etc_debconf_conf)
    (file_exists configuration_file__etc_deluser_conf)
    (file_exists configuration_file__etc_dhcpcd_conf)
    (file_exists configuration_file__etc_dracut_conf)
    (file_exists configuration_file__etc_e2scrub_conf)
    (file_exists configuration_file__etc_fprintd_conf)
    (file_exists configuration_file__etc_fuse_conf)
    (file_exists configuration_file__etc_gai_conf)
    (file_exists configuration_file__etc_hdparm_conf)
    (file_exists configuration_file__etc_host_conf)
    (file_exists configuration_file__etc_ld_so_conf)
    (file_exists configuration_file__etc_libao_conf)
    (file_exists configuration_file__etc_libaudit_conf)
    (file_exists configuration_file__etc_locale_conf)
    (file_exists configuration_file__etc_logrotate_conf)
    (file_exists configuration_file__etc_mke2fs_conf)
    (file_exists configuration_file__etc_nftables_conf)
    (file_exists configuration_file__etc_nsswitch_conf)
    (file_exists configuration_file__etc_pam_conf)
    (file_exists configuration_file__etc_pnm2ppa_conf)
    (file_exists configuration_file__etc_rsyslog_conf)
    (file_exists configuration_file__etc_rygel_conf)
    (file_exists configuration_file__etc_sensors3_conf)
    (file_exists configuration_file__etc_sudo_conf)
    (file_exists configuration_file__etc_sudo_logsrvd_conf)
    (file_exists configuration_file__etc_ucf_conf)
    (file_exists configuration_file__etc_usb_modeswitch_conf)
    (file_exists configuration_file__etc_vconsole_conf)
    (file_exists configuration_file__etc_vdpau_wrapper_cfg)
    (file_exists configuration_file__etc_xattr_conf)
    (depends_on service_unattended-upgrades_service package_unattended-upgrades)
    (depends_on service_udisks2_service package_udisks2)
    (depends_on service_systemd-user-sessions_service package_systemd)
    (depends_on service_systemd-fsck_dev-disk-by_x2duuid-9d28_x2d827c_service package_systemd)
    (depends_on service_systemd-networkd-persistent-storage_service package_systemd)
    (depends_on service_systemd-tmpfiles-setup-dev-early_service package_systemd)
    (depends_on service_snapd_recovery-chooser-trigger_service package_snapd)
    (depends_on service_dracut-pre-trigger_service package_dracut)
    (depends_on service_systemd-fsck-root_service package_systemd)
    (depends_on service_sysstat_service package_sysstat)
    (depends_on service_fwupd-refresh_service package_fwupd)
    (depends_on service_systemd-udevd_service package_systemd)
    (depends_on service_systemd-rfkill_service package_systemd)
    (depends_on service_systemd-oomd_service package_systemd-oomd)
    (depends_on service_dracut-mount_service package_dracut)
    (depends_on service_power-profiles-daemon_service package_power-profiles-daemon)
    (depends_on service_systemd-bsod_service package_systemd)
    (depends_on service_plymouth-kexec_service package_plymouth)
    (depends_on service_systemd-binfmt_service package_systemd)
    (depends_on service_systemd-firstboot_service package_systemd)
    (depends_on service_dracut-pre-udev_service package_dracut)
    (depends_on service_systemd-udev-trigger_service package_systemd)
    (depends_on service_systemd-modules-load_service package_systemd)
    (depends_on service_systemd-quotacheck-root_service package_systemd)
    (depends_on service_dracut-cmdline_service package_dracut)
    (depends_on service_systemd-update-done_service package_systemd)
    (depends_on service_systemd-sysext_service package_systemd)
    (depends_on service_systemd-pcrphase-initrd_service package_systemd)
    (depends_on service_systemd-confext_service package_systemd)
    (depends_on service_systemd-ask-password-plymouth_service package_systemd)
    (depends_on service_dracut-pre-pivot_service package_dracut)
    (depends_on service_systemd-journald_service package_systemd)
    (depends_on service_sysstat-collect_service package_sysstat)
    (depends_on service_systemd-poweroff_service package_systemd)
    (depends_on service_systemd-tmpfiles-setup-dev_service package_systemd)
    (depends_on service_systemd-quotacheck_service package_systemd)
    (depends_on service_cups_service package_cups)
    (depends_on service_systemd-networkd-wait-online_service package_systemd)
    (depends_on service_kdump-tools_service package_kdump-tools)
    (depends_on service_switcheroo-control_service package_switcheroo-control)
    (depends_on service_systemd-kexec_service package_systemd)
    (depends_on service_systemd-hibernate_service package_systemd)
    (depends_on service_dracut-shutdown-onfailure_service package_dracut)
    (depends_on service_dracut-initqueue_service package_dracut)
    (depends_on service_systemd-journal-flush_service package_systemd)
    (depends_on service_systemd-pcrphase-sysinit_service package_systemd)
    (depends_on service_systemd-vconsole-setup_service package_systemd)
    (depends_on service_kmod-static-nodes_service package_kmod)
    (depends_on service_systemd-suspend-then-hibernate_service package_systemd)
    (depends_on service_systemd-hybrid-sleep_service package_systemd)
    (depends_on service_systemd-pstore_service package_systemd)
    (depends_on service_snapd_apparmor_service package_snapd)
    (depends_on service_systemd-logind_service package_systemd)
    (depends_on service_systemd-ask-password-wall_service package_systemd)
    (depends_on service_openvpn_service package_openvpn)
    (depends_on service_snapd_snap-repair_service package_snapd)
    (depends_on service_dbus_service package_dbus)
    (depends_on service_systemd-machine-id-commit_service package_systemd)
    (depends_on service_apport-autoreport_service package_apport)
    (depends_on service_dracut-shutdown_service package_dracut)
    (depends_on service_systemd-reboot_service package_systemd)
    (depends_on service_plymouth-quit-wait_service package_plymouth)
    (depends_on service_systemd-hibernate-clear_service package_systemd)
    (depends_on service_apport_service package_apport)
    (depends_on service_fwupd_service package_fwupd)
    (depends_on service_systemd-ask-password-console_service package_systemd)
    (depends_on service_systemd-halt_service package_systemd)
    (depends_on service_snapd_seeded_service package_snapd)
    (depends_on service_systemd-pcrmachine_service package_systemd)
    (depends_on service_upower_service package_upower)
    (depends_on service_plymouth-switch-root-initramfs_service package_plymouth)
    (depends_on service_colord_service package_colord)
    (depends_on service_plymouth-halt_service package_plymouth)
    (depends_on service_systemd-udev-load-credentials_service package_systemd)
    (depends_on service_snapd_service package_snapd)
    (depends_on service_sysstat-summary_service package_sysstat)
    (depends_on service_systemd-journal-catalog-update_service package_systemd)
    (depends_on service_polkit_service package_polkitd)
    (depends_on service_systemd-tmpfiles-clean_service package_systemd)
    (depends_on service_plymouth-read-write_service package_plymouth)
    (depends_on service_systemd-tmpfiles-setup_service package_systemd)
    (depends_on service_systemd-battery-check_service package_systemd)
    (depends_on service_systemd-hibernate-resume_service package_systemd)
    (depends_on service_chrony_service package_chrony)
    (depends_on service_systemd-hostnamed_service package_systemd)
    (depends_on service_sysstat-rotate_service package_sysstat)
    (depends_on service_plymouth-reboot_service package_plymouth)
    (depends_on service_systemd-sysctl_service package_systemd)
    (depends_on service_systemd-pcrphase_service package_systemd)
    (depends_on service_dracut-pre-mount_service package_dracut)
    (depends_on service_rtkit-daemon_service package_rtkit)
    (depends_on service_plymouth-switch-root_service package_plymouth)
    (depends_on service_systemd-initctl_service package_systemd)
    (depends_on service_systemd-resolved_service package_systemd-resolved)
    (depends_on service_plymouth-start_service package_plymouth)
    (depends_on service_systemd-suspend_service package_systemd)
    (depends_on service_apparmor_service package_apparmor)
    (depends_on service_systemd-tpm2-setup-early_service package_systemd)
    (depends_on service_networkd-dispatcher_service package_networkd-dispatcher)
    (depends_on service_cups-browsed_service package_cups-browsed)
    (depends_on service_open-vm-tools_service package_open-vm-tools)
    (depends_on service_systemd-udev-settle_service package_systemd)
    (depends_on service_systemd-sysusers_service package_systemd)
    (depends_on service_systemd-networkd_service package_systemd)
    (depends_on service_snapd_core-fixup_service package_snapd)
    (depends_on service_systemd-remount-fs_service package_systemd)
    (depends_on service_ufw_service package_ufw)
    (depends_on service_systemd-hwdb-update_service package_systemd)
    (depends_on service_snapd_autoimport_service package_snapd)
    (depends_on service_snapd_failure_service package_snapd)
    (depends_on service_gdm_service package_gdm3)
    (depends_on service_plymouth-quit_service package_plymouth)
    (depends_on service_systemd-random-seed_service package_systemd)
    (depends_on service_cron_service package_cron)
    (depends_on service_snapd_system-shutdown_service package_snapd)
    (depends_on service_console-setup_service package_console-setup)
    (depends_on service_rsyslog_service package_rsyslog)
    (depends_on service_systemd-tpm2-setup_service package_systemd)
    (depends_on service_logrotate_service package_logrotate)
    (depends_on service_systemd-soft-reboot_service package_systemd)
    (depends_on service_avahi-daemon_service package_avahi-daemon)
    (depends_on service_plymouth-poweroff_service package_plymouth)
    (configures configuration_file__etc_rsyslog_conf service_rsyslog_service)
    (configures configuration_file__etc_logrotate_conf service_logrotate_service)
    (member_of user_root group_root)
    (member_of user_sync group_nogroup)
    (member_of user__apt group_nogroup)
    (member_of user_nobody group_nogroup)
    (member_of user_dhcpcd group_nogroup)
    (member_of user_syslog group_syslog)
    (member_of user_syslog group_adm)
    (member_of user_dnsmasq group_nogroup)
    (member_of user_usbmux group_plugdev)
    (member_of user_cups-pk-helper group_lpadmin)
    (member_of user_cups-browsed group_lpadmin)
    (member_of user_gnome-initial-setup group_nogroup)
    (member_of user_resbears group_resbears)
    (member_of user_resbears group_adm)
    (member_of user_resbears group_cdrom)
    (member_of user_resbears group_sudo)
    (member_of user_resbears group_dip)
    (member_of user_resbears group_plugdev)
    (member_of user_resbears group_users)
    (member_of user_resbears group_lpadmin)
    (file_owned_by configuration_file__etc_adduser_conf user_root)
    (file_owned_by configuration_file__etc_brltty_conf user_root)
    (file_owned_by configuration_file__etc_ca-certificates_conf user_root)
    (file_owned_by configuration_file__etc_debconf_conf user_root)
    (file_owned_by configuration_file__etc_deluser_conf user_root)
    (file_owned_by configuration_file__etc_dhcpcd_conf user_root)
    (file_owned_by configuration_file__etc_dracut_conf user_root)
    (file_owned_by configuration_file__etc_e2scrub_conf user_root)
    (file_owned_by configuration_file__etc_fprintd_conf user_root)
    (file_owned_by configuration_file__etc_fuse_conf user_root)
    (file_owned_by configuration_file__etc_gai_conf user_root)
    (file_owned_by configuration_file__etc_hdparm_conf user_root)
    (file_owned_by configuration_file__etc_host_conf user_root)
    (file_owned_by configuration_file__etc_ld_so_conf user_root)
    (file_owned_by configuration_file__etc_libao_conf user_root)
    (file_owned_by configuration_file__etc_libaudit_conf user_root)
    (file_owned_by configuration_file__etc_locale_conf user_root)
    (file_owned_by configuration_file__etc_logrotate_conf user_root)
    (file_owned_by configuration_file__etc_mke2fs_conf user_root)
    (file_owned_by configuration_file__etc_nftables_conf user_root)
    (file_owned_by configuration_file__etc_nsswitch_conf user_root)
    (file_owned_by configuration_file__etc_pam_conf user_root)
    (file_owned_by configuration_file__etc_pnm2ppa_conf user_root)
    (file_owned_by configuration_file__etc_rsyslog_conf user_root)
    (file_owned_by configuration_file__etc_rygel_conf user_root)
    (file_owned_by configuration_file__etc_sensors3_conf user_root)
    (file_owned_by configuration_file__etc_sudo_conf user_root)
    (file_owned_by configuration_file__etc_sudo_logsrvd_conf user_root)
    (file_owned_by configuration_file__etc_ucf_conf user_root)
    (file_owned_by configuration_file__etc_usb_modeswitch_conf user_root)
    (file_owned_by configuration_file__etc_vconsole_conf user_root)
    (file_owned_by configuration_file__etc_vdpau_wrapper_cfg user_root)
    (file_owned_by configuration_file__etc_xattr_conf user_root)
    (can_escalate user_resbears)
    (port_bound_by port_6_48369 process_code_7)
    (port_bound_by port_6_5878 process_code_13)
    (port_bound_by port_6_24855 process_code_7)
    (port_bound_by port_6_37021 process_code_12)
    (process_owned_by process_systemd user_root)
    (process_owned_by process_vgauthservice user_root)
    (process_owned_by process_vmtoolsd user_root)
    (process_owned_by process_chronyd-starter user_root)
    (process_owned_by process_networkd-dispat user_root)
    (process_owned_by process_accounts-daemon user_root)
    (process_owned_by process_cron user_root)
    (process_owned_by process_switcheroo-cont user_root)
    (process_owned_by process_systemd-logind user_root)
    (process_owned_by process_udisksd user_root)
    (process_owned_by process_rsyslogd user_syslog)
    (process_owned_by process_networkmanager user_root)
    (process_owned_by process_wpa_supplicant user_root)
    (process_owned_by process_modemmanager user_root)
    (process_owned_by process_cupsd user_root)
    (process_owned_by process_unattended-upgr user_root)
    (process_owned_by process_gdm3 user_root)
    (process_owned_by process_cups-browsed user_cups-browsed)
    (process_owned_by process_kthreadd user_root)
    (process_owned_by process_code user_resbears)
    (process_owned_by process_upowerd user_root)
    (process_owned_by process_irq_16-vmwgfx user_root)
    (process_owned_by process_bash user_resbears)
    (process_owned_by process_ruff user_resbears)
    (process_owned_by process_python user_resbears)
    (process_owned_by process_osqueryi user_resbears)
    (process_owned_by process_power-profiles- user_root)
    (process_owned_by process_gdm-session-wor user_root)
    (process_owned_by process_systemd_1 user_resbears)
    (process_owned_by process__sd-pam_ user_resbears)
    (process_owned_by process_dbus-daemon user_resbears)
    (process_owned_by process_pipewire user_resbears)
    (process_owned_by process_pipewire_1 user_resbears)
    (process_owned_by process_gnome-keyring-d user_resbears)
    (process_owned_by process_mpris-proxy user_resbears)
    (process_owned_by process_wireplumber user_resbears)
    (process_owned_by process_pipewire-pulse user_resbears)
    (process_owned_by process_gdm-wayland-ses user_resbears)
    (process_owned_by process_gnome-session-i user_resbears)
    (process_owned_by process_xdg-document-po user_resbears)
    (process_owned_by process_xdg-permission- user_resbears)
    (process_owned_by process_fusermount3 user_root)
    (process_owned_by process_gcr-ssh-agent user_resbears)
    (process_owned_by process_gnome-session-c user_resbears)
    (process_owned_by process_ssh-agent user_resbears)
    (process_owned_by process_gvfsd user_resbears)
    (process_owned_by process_gvfsd-fuse user_resbears)
    (process_owned_by process_gnome-session-s user_resbears)
    (process_owned_by process_gnome-shell user_resbears)
    (process_owned_by process_at-spi-bus-laun user_resbears)
    (process_owned_by process_dbus-daemon_1 user_resbears)
    (process_owned_by process_at-spi2-registr user_resbears)
    (process_owned_by process_gnome-shell-cal user_resbears)
    (process_owned_by process_evolution-sourc user_resbears)
    (process_owned_by process_gjs user_resbears)
    (process_owned_by process_ibus-daemon user_resbears)
    (process_owned_by process_gsd-a11y-settin user_resbears)
    (process_owned_by process_gsd-color user_resbears)
    (process_owned_by process_gsd-datetime user_resbears)
    (process_owned_by process_gsd-housekeepin user_resbears)
    (process_owned_by process_gsd-keyboard user_resbears)
    (process_owned_by process_gsd-media-keys user_resbears)
    (process_owned_by process_gsd-power user_resbears)
    (process_owned_by process_gsd-print-notif user_resbears)
    (process_owned_by process_gsd-rfkill user_resbears)
    (process_owned_by process_gsd-screensaver user_resbears)
    (process_owned_by process_sh user_resbears)
    (process_owned_by process_xwayland user_resbears)
    (process_owned_by process_gsd-sharing user_resbears)
    (process_owned_by process_snap user_resbears)
    (process_owned_by process_ubuntu-advantag user_resbears)
    (process_owned_by process_update-notifier user_resbears)
    (process_owned_by process_evolution-alarm user_resbears)
    (process_owned_by process_gsd-smartcard user_resbears)
    (process_owned_by process_vmware-user-sui user_resbears)
    (process_owned_by process_ubuntu-report user_resbears)
    (process_owned_by process_gsd-disk-utilit user_resbears)
    (process_owned_by process_vmtoolsd_1 user_resbears)
    (process_owned_by process_gsd-sound user_resbears)
    (process_owned_by process_gjs_1 user_resbears)
    (process_owned_by process_goa-daemon user_resbears)
    (process_owned_by process_bwrap user_resbears)
    (process_owned_by process_gsd-usb-protect user_resbears)
    (process_owned_by process_gsd-wwan user_resbears)
    (process_owned_by process_bwrap_1 user_resbears)
    (process_owned_by process_glycin-image-rs user_resbears)
    (process_owned_by process_ibus-dconf user_resbears)
    (process_owned_by process_ibus-extension- user_resbears)
    (process_owned_by process_gsd-printer user_resbears)
    (process_owned_by process_gvfs-udisks2-vo user_resbears)
    (process_owned_by process_pool_workqueue_release user_root)
    (process_owned_by process_ibus-portal user_resbears)
    (process_owned_by process_evolution-calen user_resbears)
    (process_owned_by process_goa-identity-se user_resbears)
    (process_owned_by process_localsearch-3 user_resbears)
    (process_owned_by process_gvfs-gphoto2-vo user_resbears)
    (process_owned_by process_evolution-addre user_resbears)
    (process_owned_by process_gvfs-goa-volume user_resbears)
    (process_owned_by process_gvfsd-metadata user_resbears)
    (process_owned_by process_gvfs-afc-volume user_resbears)
    (process_owned_by process_gvfs-mtp-volume user_resbears)
    (process_owned_by process_ibus-engine-sim user_resbears)
    (process_owned_by process_dconf-service user_resbears)
    (process_owned_by process_gvfsd-trash user_resbears)
    (process_owned_by process_scsi_eh_2 user_root)
    (process_owned_by process_gjs_2 user_resbears)
    (process_owned_by process_scsi_eh_3 user_root)
    (process_owned_by process_scsi_eh_4 user_root)
    (process_owned_by process_scsi_eh_5 user_root)
    (process_owned_by process_gsd-xsettings user_resbears)
    (process_owned_by process_mutter-x11-fram user_resbears)
    (process_owned_by process_xdg-desktop-por user_resbears)
    (process_owned_by process_scsi_eh_6 user_root)
    (process_owned_by process_xdg-desktop-por_1 user_resbears)
    (process_owned_by process_scsi_eh_7 user_root)
    (process_owned_by process_ibus-x11 user_resbears)
    (process_owned_by process_scsi_eh_8 user_root)
    (process_owned_by process_scsi_eh_9 user_root)
    (process_owned_by process_xdg-desktop-por_2 user_resbears)
    (process_owned_by process_scsi_eh_10 user_root)
    (process_owned_by process_scsi_eh_11 user_root)
    (process_owned_by process_scsi_eh_12 user_root)
    (process_owned_by process_scsi_eh_13 user_root)
    (process_owned_by process_scsi_eh_14 user_root)
    (process_owned_by process_scsi_eh_15 user_root)
    (process_owned_by process_obexd user_resbears)
    (process_owned_by process_scsi_eh_16 user_root)
    (process_owned_by process_scsi_eh_17 user_root)
    (process_owned_by process_scsi_eh_18 user_root)
    (process_owned_by process_scsi_eh_19 user_root)
    (process_owned_by process_scsi_eh_20 user_root)
    (process_owned_by process_scsi_eh_21 user_root)
    (process_owned_by process_scsi_eh_22 user_root)
    (process_owned_by process_scsi_eh_23 user_root)
    (process_owned_by process_scsi_eh_24 user_root)
    (process_owned_by process_scsi_eh_25 user_root)
    (process_owned_by process_scsi_eh_26 user_root)
    (process_owned_by process_scsi_eh_27 user_root)
    (process_owned_by process_scsi_eh_28 user_root)
    (process_owned_by process_scsi_eh_29 user_root)
    (process_owned_by process_scsi_eh_30 user_root)
    (process_owned_by process_scsi_eh_31 user_root)
    (process_owned_by process_scsi_eh_32 user_root)
    (process_owned_by process_code_1 user_resbears)
    (process_owned_by process_code_2 user_resbears)
    (process_owned_by process_code_3 user_resbears)
    (process_owned_by process_chrome_crashpad user_resbears)
    (process_owned_by process_kdevtmpfs user_root)
    (process_owned_by process_code_4 user_resbears)
    (process_owned_by process_code_5 user_resbears)
    (process_owned_by process_code_6 user_resbears)
    (process_owned_by process_code_7 user_resbears)
    (process_owned_by process_code_8 user_resbears)
    (process_owned_by process_code_9 user_resbears)
    (process_owned_by process_code_10 user_resbears)
    (process_owned_by process_pet user_resbears)
    (process_owned_by process_bash_1 user_resbears)
    (process_owned_by process_kauditd user_root)
    (process_owned_by process_jbd2_sda2-8 user_root)
    (process_owned_by process_khungtaskd user_root)
    (process_owned_by process_code_11 user_resbears)
    (process_owned_by process_code_12 user_resbears)
    (process_owned_by process_oom_reaper user_root)
    (process_owned_by process_systemd-journal user_root)
    (process_owned_by process_kcompactd0 user_root)
    (process_owned_by process_ksmd user_root)
    (process_owned_by process_code_13 user_resbears)
    (process_owned_by process_khugepaged user_root)
    (process_owned_by process_systemd-udevd user_root)
    (process_owned_by process_psimon user_root)
    (process_owned_by process_irq_9-acpi user_root)
    (process_owned_by process_snapd user_root)
    (process_owned_by process_irq_26-vmw_vmci user_root)
    (process_owned_by process_irq_27-vmw_vmci user_root)
    (process_owned_by process_irq_28-vmw_vmci user_root)
    (process_owned_by process_kswapd0 user_root)
    (process_owned_by process_ecryptfs-kthread user_root)
    (process_owned_by process_snapd-desktop-i user_resbears)
    (process_owned_by process_snapd-desktop-i_1 user_resbears)
    (process_owned_by process_scsi_eh_0 user_root)
    (process_owned_by process_scsi_eh_1 user_root)
    (process_owned_by process_psimon_1 user_root)
    (process_owned_by process_fwupd user_root)
    (process_owned_by process_vmware-vmblock- user_root)
    (depends_on service_unattended-upgrades_service package_unattended-upgrades)
    (depends_on service_udisks2_service package_udisks2)
    (depends_on service_systemd-user-sessions_service package_systemd)
    (depends_on service_systemd-fsck_dev-disk-by_x2duuid-9d28_x2d827c_service package_systemd)
    (depends_on service_systemd-networkd-persistent-storage_service package_systemd)
    (depends_on service_systemd-tmpfiles-setup-dev-early_service package_systemd)
    (depends_on service_snapd_recovery-chooser-trigger_service package_snapd)
    (depends_on service_dracut-pre-trigger_service package_dracut)
    (depends_on service_systemd-fsck-root_service package_systemd)
    (depends_on service_sysstat_service package_sysstat)
    (depends_on service_fwupd-refresh_service package_fwupd)
    (depends_on service_systemd-udevd_service package_systemd)
    (depends_on service_systemd-rfkill_service package_systemd)
    (depends_on service_systemd-oomd_service package_systemd-oomd)
    (depends_on service_dracut-mount_service package_dracut)
    (depends_on service_power-profiles-daemon_service package_power-profiles-daemon)
    (depends_on service_systemd-bsod_service package_systemd)
    (depends_on service_plymouth-kexec_service package_plymouth)
    (depends_on service_systemd-binfmt_service package_systemd)
    (depends_on service_systemd-firstboot_service package_systemd)
    (depends_on service_dracut-pre-udev_service package_dracut)
    (depends_on service_systemd-udev-trigger_service package_systemd)
    (depends_on service_systemd-modules-load_service package_systemd)
    (depends_on service_systemd-quotacheck-root_service package_systemd)
    (depends_on service_dracut-cmdline_service package_dracut)
    (depends_on service_systemd-update-done_service package_systemd)
    (depends_on service_systemd-sysext_service package_systemd)
    (depends_on service_systemd-pcrphase-initrd_service package_systemd)
    (depends_on service_systemd-confext_service package_systemd)
    (depends_on service_systemd-ask-password-plymouth_service package_systemd)
    (depends_on service_dracut-pre-pivot_service package_dracut)
    (depends_on service_systemd-journald_service package_systemd)
    (depends_on service_sysstat-collect_service package_sysstat)
    (depends_on service_systemd-poweroff_service package_systemd)
    (depends_on service_systemd-tmpfiles-setup-dev_service package_systemd)
    (depends_on service_systemd-quotacheck_service package_systemd)
    (depends_on service_cups_service package_cups)
    (depends_on service_systemd-networkd-wait-online_service package_systemd)
    (depends_on service_kdump-tools_service package_kdump-tools)
    (depends_on service_switcheroo-control_service package_switcheroo-control)
    (depends_on service_systemd-kexec_service package_systemd)
    (depends_on service_systemd-hibernate_service package_systemd)
    (depends_on service_dracut-shutdown-onfailure_service package_dracut)
    (depends_on service_dracut-initqueue_service package_dracut)
    (depends_on service_systemd-journal-flush_service package_systemd)
    (depends_on service_systemd-pcrphase-sysinit_service package_systemd)
    (depends_on service_systemd-vconsole-setup_service package_systemd)
    (depends_on service_kmod-static-nodes_service package_kmod)
    (depends_on service_systemd-suspend-then-hibernate_service package_systemd)
    (depends_on service_systemd-hybrid-sleep_service package_systemd)
    (depends_on service_systemd-pstore_service package_systemd)
    (depends_on service_snapd_apparmor_service package_snapd)
    (depends_on service_systemd-logind_service package_systemd)
    (depends_on service_systemd-ask-password-wall_service package_systemd)
    (depends_on service_openvpn_service package_openvpn)
    (depends_on service_snapd_snap-repair_service package_snapd)
    (depends_on service_dbus_service package_dbus)
    (depends_on service_systemd-machine-id-commit_service package_systemd)
    (depends_on service_apport-autoreport_service package_apport)
    (depends_on service_dracut-shutdown_service package_dracut)
    (depends_on service_systemd-reboot_service package_systemd)
    (depends_on service_plymouth-quit-wait_service package_plymouth)
    (depends_on service_systemd-hibernate-clear_service package_systemd)
    (depends_on service_apport_service package_apport)
    (depends_on service_fwupd_service package_fwupd)
    (depends_on service_systemd-ask-password-console_service package_systemd)
    (depends_on service_systemd-halt_service package_systemd)
    (depends_on service_snapd_seeded_service package_snapd)
    (depends_on service_systemd-pcrmachine_service package_systemd)
    (depends_on service_upower_service package_upower)
    (depends_on service_plymouth-switch-root-initramfs_service package_plymouth)
    (depends_on service_colord_service package_colord)
    (depends_on service_plymouth-halt_service package_plymouth)
    (depends_on service_systemd-udev-load-credentials_service package_systemd)
    (depends_on service_snapd_service package_snapd)
    (depends_on service_sysstat-summary_service package_sysstat)
    (depends_on service_systemd-journal-catalog-update_service package_systemd)
    (depends_on service_polkit_service package_polkitd)
    (depends_on service_systemd-tmpfiles-clean_service package_systemd)
    (depends_on service_plymouth-read-write_service package_plymouth)
    (depends_on service_systemd-tmpfiles-setup_service package_systemd)
    (depends_on service_systemd-battery-check_service package_systemd)
    (depends_on service_systemd-hibernate-resume_service package_systemd)
    (depends_on service_chrony_service package_chrony)
    (depends_on service_systemd-hostnamed_service package_systemd)
    (depends_on service_sysstat-rotate_service package_sysstat)
    (depends_on service_plymouth-reboot_service package_plymouth)
    (depends_on service_systemd-sysctl_service package_systemd)
    (depends_on service_systemd-pcrphase_service package_systemd)
    (depends_on service_dracut-pre-mount_service package_dracut)
    (depends_on service_rtkit-daemon_service package_rtkit)
    (depends_on service_plymouth-switch-root_service package_plymouth)
    (depends_on service_systemd-initctl_service package_systemd)
    (depends_on service_systemd-resolved_service package_systemd-resolved)
    (depends_on service_plymouth-start_service package_plymouth)
    (depends_on service_systemd-suspend_service package_systemd)
    (depends_on service_apparmor_service package_apparmor)
    (depends_on service_systemd-tpm2-setup-early_service package_systemd)
    (depends_on service_networkd-dispatcher_service package_networkd-dispatcher)
    (depends_on service_cups-browsed_service package_cups-browsed)
    (depends_on service_open-vm-tools_service package_open-vm-tools)
    (depends_on service_systemd-udev-settle_service package_systemd)
    (depends_on service_systemd-sysusers_service package_systemd)
    (depends_on service_systemd-networkd_service package_systemd)
    (depends_on service_snapd_core-fixup_service package_snapd)
    (depends_on service_systemd-remount-fs_service package_systemd)
    (depends_on service_ufw_service package_ufw)
    (depends_on service_systemd-hwdb-update_service package_systemd)
    (depends_on service_snapd_autoimport_service package_snapd)
    (depends_on service_snapd_failure_service package_snapd)
    (depends_on service_gdm_service package_gdm3)
    (depends_on service_plymouth-quit_service package_plymouth)
    (depends_on service_systemd-random-seed_service package_systemd)
    (depends_on service_cron_service package_cron)
    (depends_on service_snapd_system-shutdown_service package_snapd)
    (depends_on service_console-setup_service package_console-setup)
    (depends_on service_rsyslog_service package_rsyslog)
    (depends_on service_systemd-tpm2-setup_service package_systemd)
    (depends_on service_logrotate_service package_logrotate)
    (depends_on service_systemd-soft-reboot_service package_systemd)
    (depends_on service_avahi-daemon_service package_avahi-daemon)
    (depends_on service_plymouth-poweroff_service package_plymouth)
    (configures configuration_file__etc_rsyslog_conf service_rsyslog_service)
    (configures configuration_file__etc_logrotate_conf service_logrotate_service)
    (member_of user_root group_root)
    (member_of user_sync group_nogroup)
    (member_of user__apt group_nogroup)
    (member_of user_nobody group_nogroup)
    (member_of user_dhcpcd group_nogroup)
    (member_of user_syslog group_syslog)
    (member_of user_syslog group_adm)
    (member_of user_dnsmasq group_nogroup)
    (member_of user_usbmux group_plugdev)
    (member_of user_cups-pk-helper group_lpadmin)
    (member_of user_cups-browsed group_lpadmin)
    (member_of user_gnome-initial-setup group_nogroup)
    (member_of user_resbears group_resbears)
    (member_of user_resbears group_adm)
    (member_of user_resbears group_cdrom)
    (member_of user_resbears group_sudo)
    (member_of user_resbears group_dip)
    (member_of user_resbears group_plugdev)
    (member_of user_resbears group_users)
    (member_of user_resbears group_lpadmin)
    (can_escalate user_resbears)
    (network_available)
  )

  (:goal
    (and
      (network_available)
    )
  )
)